// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bbk/app/system/internal/dao/internal"
)

// enumDao is the data access object for the table free_enum.
// You can define custom methods on it to extend its functionality as needed.
type enumDao struct {
	*internal.EnumDao
}

var (
	// Enum is a globally accessible object for table free_enum operations.
	Enum = enumDao{internal.NewEnumDao()}
)

// Add your custom methods and functionality below.
