// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/system/internal/dao/internal"
)

// systemConfigDao is the data access object for the table free_system_config.
// You can define custom methods on it to extend its functionality as needed.
type systemConfigDao struct {
	*internal.SystemConfigDao
}

var (
	// SystemConfig is a globally accessible object for table free_system_config operations.
	SystemConfig = systemConfigDao{internal.NewSystemConfigDao()}
)

// Add your custom methods and functionality below.
