// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/system/internal/dao/internal"
)

// systemEnumDataDao is the data access object for the table free_system_enum_data.
// You can define custom methods on it to extend its functionality as needed.
type systemEnumDataDao struct {
	*internal.SystemEnumDataDao
}

var (
	// SystemEnumData is a globally accessible object for table free_system_enum_data operations.
	SystemEnumData = systemEnumDataDao{internal.NewSystemEnumDataDao()}
)

// Add your custom methods and functionality below.
