// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/system/internal/dao/internal"
)

// systemEnumTypeDao is the data access object for the table free_system_enum_type.
// You can define custom methods on it to extend its functionality as needed.
type systemEnumTypeDao struct {
	*internal.SystemEnumTypeDao
}

var (
	// SystemEnumType is a globally accessible object for table free_system_enum_type operations.
	SystemEnumType = systemEnumTypeDao{internal.NewSystemEnumTypeDao()}
)

// Add your custom methods and functionality below.
