// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: role/v1/role.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色编码(唯一)
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty" dc:"角色编码(唯一)" v:"required|length:1,64#角色编码不能为空|角色编码长度必须在1-64之间"` // v:required|length:1,64#角色编码不能为空|角色编码长度必须在1-64之间
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"角色名称" v:"required|length:1,64#角色名称不能为空|角色名称长度必须在1-64之间"` // v:required|length:1,64#角色名称不能为空|角色名称长度必须在1-64之间
	// 状态:role_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:role_status" v:"required|enum:role_status#状态不能为空"` // v:required|enum:role_status#状态不能为空
	// 备注
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty" dc:"备注"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateRoleRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRes) Reset() {
	*x = CreateRoleRes{}
	mi := &file_role_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRes) ProtoMessage() {}

func (x *CreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRes.ProtoReflect.Descriptor instead.
func (*CreateRoleRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRoleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"角色名称" v:"length:1,64#角色名称长度必须在1-64之间"` // v:length:1,64#角色名称长度必须在1-64之间
	// 状态:role_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:role_status" v:"enum:role_status"` // v:enum:role_status
	// 备注
	Remark        string `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty" dc:"备注"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_role_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRoleReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateRoleRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRes) Reset() {
	*x = UpdateRoleRes{}
	mi := &file_role_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRes) ProtoMessage() {}

func (x *UpdateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRes.ProtoReflect.Descriptor instead.
func (*UpdateRoleRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoleRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRoleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReq) Reset() {
	*x = DeleteRoleReq{}
	mi := &file_role_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReq) ProtoMessage() {}

func (x *DeleteRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRoleRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRes) Reset() {
	*x = DeleteRoleRes{}
	mi := &file_role_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRes) ProtoMessage() {}

func (x *DeleteRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRes.ProtoReflect.Descriptor instead.
func (*DeleteRoleRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRoleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleReq) Reset() {
	*x = GetRoleReq{}
	mi := &file_role_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleReq) ProtoMessage() {}

func (x *GetRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleReq.ProtoReflect.Descriptor instead.
func (*GetRoleReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID"`
	// 角色编码(唯一)
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty" dc:"角色编码(唯一)"`
	// 角色名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"角色名称"`
	// 状态:role_status
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty" dc:"状态:role_status"`
	// 是否系统内置0:否,1:是
	IsSystem bool `protobuf:"varint,5,opt,name=isSystem,proto3" json:"isSystem,omitempty" dc:"是否系统内置0:否,1:是"`
	// 备注
	Remark string `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty" dc:"备注"`
	// 创建时间
	CreateAt int64 `protobuf:"varint,9,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	// 更新时间
	UpdateAt      int64 `protobuf:"varint,10,opt,name=updateAt,proto3" json:"updateAt,omitempty" dc:"更新时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRes) Reset() {
	*x = GetRoleRes{}
	mi := &file_role_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRes) ProtoMessage() {}

func (x *GetRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRes.ProtoReflect.Descriptor instead.
func (*GetRoleRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRoleRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetRoleRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRoleRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetRoleRes) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *GetRoleRes) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GetRoleRes) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GetRoleRes) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type ListRoleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" dc:"页码" v:"min:1#页码必须大于0"` // v:min:1#页码必须大于0
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量" v:"min:1|max:100#每页数量必须大于0|每页数量不能超过100"` // v:min:1|max:100#每页数量必须大于0|每页数量不能超过100
	// 对 code/name 模糊
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty" dc:"对 code/name 模糊"`
	// 状态:role_status
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty" dc:"状态:role_status" v:"enum:role_status"` // v:enum:role_status
	// 是否系统内置0:否,1:是
	IsSystem      int64 `protobuf:"varint,5,opt,name=isSystem,proto3" json:"isSystem,omitempty" dc:"是否系统内置0:否,1:是"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleReq) Reset() {
	*x = ListRoleReq{}
	mi := &file_role_v1_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReq) ProtoMessage() {}

func (x *ListRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReq.ProtoReflect.Descriptor instead.
func (*ListRoleReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoleReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoleReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListRoleReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRoleReq) GetIsSystem() int64 {
	if x != nil {
		return x.IsSystem
	}
	return 0
}

type ListRoleRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色列表
	List []*GetRoleRes `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"角色列表"`
	// 总数
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"总数"`
	// 页码
	Page int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" dc:"页码"`
	// 每页数量
	PageSize      int64 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRes) Reset() {
	*x = ListRoleRes{}
	mi := &file_role_v1_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRes) ProtoMessage() {}

func (x *ListRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRes.ProtoReflect.Descriptor instead.
func (*ListRoleRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoleRes) GetList() []*GetRoleRes {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRoleRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRoleRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRolePositionListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" dc:"页码" v:"min:1#页码必须大于0"` // v:min:1#页码必须大于0
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量" v:"min:1|max:100#每页数量必须大于0|每页数量不能超过100"` // v:min:1|max:100#每页数量必须大于0|每页数量不能超过100
	// 对 职务名称模糊 模糊
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty" dc:"对 职务名称模糊 模糊"`
	// 角色ID
	RoleId        int64 `protobuf:"varint,4,opt,name=roleId,proto3" json:"roleId,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePositionListReq) Reset() {
	*x = GetRolePositionListReq{}
	mi := &file_role_v1_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePositionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePositionListReq) ProtoMessage() {}

func (x *GetRolePositionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePositionListReq.ProtoReflect.Descriptor instead.
func (*GetRolePositionListReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{10}
}

func (x *GetRolePositionListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRolePositionListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRolePositionListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetRolePositionListReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetRolePositionListRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务列表
	List []*PositionItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"职务列表"`
	// 总数
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"总数"`
	// 页码
	Page int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" dc:"页码"`
	// 每页数量
	PageSize      int64 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePositionListRes) Reset() {
	*x = GetRolePositionListRes{}
	mi := &file_role_v1_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePositionListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePositionListRes) ProtoMessage() {}

func (x *GetRolePositionListRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePositionListRes.ProtoReflect.Descriptor instead.
func (*GetRolePositionListRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{11}
}

func (x *GetRolePositionListRes) GetList() []*PositionItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetRolePositionListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetRolePositionListRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRolePositionListRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PositionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	PositionId int64 `protobuf:"varint,1,opt,name=positionId,proto3" json:"positionId,omitempty" dc:"职务ID"`
	// 职务名称
	PositionName string `protobuf:"bytes,3,opt,name=positionName,proto3" json:"positionName,omitempty" dc:"职务名称"`
	// 职务状态
	PositionStatus string `protobuf:"bytes,2,opt,name=positionStatus,proto3" json:"positionStatus,omitempty" dc:"职务状态"`
	// 绑定时间
	CreateAt      string `protobuf:"bytes,4,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"绑定时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionItem) Reset() {
	*x = PositionItem{}
	mi := &file_role_v1_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionItem) ProtoMessage() {}

func (x *PositionItem) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionItem.ProtoReflect.Descriptor instead.
func (*PositionItem) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{12}
}

func (x *PositionItem) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *PositionItem) GetPositionName() string {
	if x != nil {
		return x.PositionName
	}
	return ""
}

func (x *PositionItem) GetPositionStatus() string {
	if x != nil {
		return x.PositionStatus
	}
	return ""
}

func (x *PositionItem) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

// 批量绑定职务到角色（覆盖式）
type BatchAssignRolePositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	RoleId int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	// 职务ID列表
	PositionIds   []int64 `protobuf:"varint,2,rep,packed,name=positionIds,proto3" json:"positionIds,omitempty" dc:"职务ID列表"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAssignRolePositionReq) Reset() {
	*x = BatchAssignRolePositionReq{}
	mi := &file_role_v1_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAssignRolePositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAssignRolePositionReq) ProtoMessage() {}

func (x *BatchAssignRolePositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAssignRolePositionReq.ProtoReflect.Descriptor instead.
func (*BatchAssignRolePositionReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{13}
}

func (x *BatchAssignRolePositionReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BatchAssignRolePositionReq) GetPositionIds() []int64 {
	if x != nil {
		return x.PositionIds
	}
	return nil
}

type BatchAssignRolePositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAssignRolePositionRes) Reset() {
	*x = BatchAssignRolePositionRes{}
	mi := &file_role_v1_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAssignRolePositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAssignRolePositionRes) ProtoMessage() {}

func (x *BatchAssignRolePositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAssignRolePositionRes.ProtoReflect.Descriptor instead.
func (*BatchAssignRolePositionRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{14}
}

func (x *BatchAssignRolePositionRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 查询角色当前绑定职务ID集合（表单回显）
type GetRolePositionIdsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	RoleId        int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePositionIdsReq) Reset() {
	*x = GetRolePositionIdsReq{}
	mi := &file_role_v1_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePositionIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePositionIdsReq) ProtoMessage() {}

func (x *GetRolePositionIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePositionIdsReq.ProtoReflect.Descriptor instead.
func (*GetRolePositionIdsReq) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{15}
}

func (x *GetRolePositionIdsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type GetRolePositionIdsRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID列表
	PositionIds   []int64 `protobuf:"varint,1,rep,packed,name=positionIds,proto3" json:"positionIds,omitempty" dc:"职务ID列表"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePositionIdsRes) Reset() {
	*x = GetRolePositionIdsRes{}
	mi := &file_role_v1_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePositionIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePositionIdsRes) ProtoMessage() {}

func (x *GetRolePositionIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_role_v1_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePositionIdsRes.ProtoReflect.Descriptor instead.
func (*GetRolePositionIdsRes) Descriptor() ([]byte, []int) {
	return file_role_v1_role_proto_rawDescGZIP(), []int{16}
}

func (x *GetRolePositionIdsRes) GetPositionIds() []int64 {
	if x != nil {
		return x.PositionIds
	}
	return nil
}

var File_role_v1_role_proto protoreflect.FileDescriptor

const file_role_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x12role/v1/role.proto\x12\arole.v1\"g\n" +
	"\rCreateRoleReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\x1f\n" +
	"\rCreateRoleRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"c\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\")\n" +
	"\rUpdateRoleRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1f\n" +
	"\rDeleteRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\rDeleteRoleRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1c\n" +
	"\n" +
	"GetRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc8\x01\n" +
	"\n" +
	"GetRoleRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bisSystem\x18\x05 \x01(\bR\bisSystem\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x1a\n" +
	"\bcreateAt\x18\t \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\n" +
	" \x01(\x03R\bupdateAt\"\x8b\x01\n" +
	"\vListRoleReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bisSystem\x18\x05 \x01(\x03R\bisSystem\"|\n" +
	"\vListRoleRes\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.role.v1.GetRoleResR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"z\n" +
	"\x16GetRolePositionListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06roleId\x18\x04 \x01(\x03R\x06roleId\"\x89\x01\n" +
	"\x16GetRolePositionListRes\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.role.v1.PositionItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\x96\x01\n" +
	"\fPositionItem\x12\x1e\n" +
	"\n" +
	"positionId\x18\x01 \x01(\x03R\n" +
	"positionId\x12\"\n" +
	"\fpositionName\x18\x03 \x01(\tR\fpositionName\x12&\n" +
	"\x0epositionStatus\x18\x02 \x01(\tR\x0epositionStatus\x12\x1a\n" +
	"\bcreateAt\x18\x04 \x01(\tR\bcreateAt\"V\n" +
	"\x1aBatchAssignRolePositionReq\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12 \n" +
	"\vpositionIds\x18\x02 \x03(\x03R\vpositionIds\"6\n" +
	"\x1aBatchAssignRolePositionRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x15GetRolePositionIdsReq\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\"9\n" +
	"\x15GetRolePositionIdsRes\x12 \n" +
	"\vpositionIds\x18\x01 \x03(\x03R\vpositionIds2\xc1\x04\n" +
	"\x04Role\x12<\n" +
	"\n" +
	"CreateRole\x12\x16.role.v1.CreateRoleReq\x1a\x16.role.v1.CreateRoleRes\x12<\n" +
	"\n" +
	"UpdateRole\x12\x16.role.v1.UpdateRoleReq\x1a\x16.role.v1.UpdateRoleRes\x12<\n" +
	"\n" +
	"DeleteRole\x12\x16.role.v1.DeleteRoleReq\x1a\x16.role.v1.DeleteRoleRes\x123\n" +
	"\aGetRole\x12\x13.role.v1.GetRoleReq\x1a\x13.role.v1.GetRoleRes\x126\n" +
	"\bListRole\x12\x14.role.v1.ListRoleReq\x1a\x14.role.v1.ListRoleRes\x12W\n" +
	"\x13GetRolePositionList\x12\x1f.role.v1.GetRolePositionListReq\x1a\x1f.role.v1.GetRolePositionListRes\x12c\n" +
	"\x17BatchAssignRolePosition\x12#.role.v1.BatchAssignRolePositionReq\x1a#.role.v1.BatchAssignRolePositionRes\x12T\n" +
	"\x12GetRolePositionIds\x12\x1e.role.v1.GetRolePositionIdsReq\x1a\x1e.role.v1.GetRolePositionIdsResB\x0fZ\r./api/role/v1b\x06proto3"

var (
	file_role_v1_role_proto_rawDescOnce sync.Once
	file_role_v1_role_proto_rawDescData []byte
)

func file_role_v1_role_proto_rawDescGZIP() []byte {
	file_role_v1_role_proto_rawDescOnce.Do(func() {
		file_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_v1_role_proto_rawDesc), len(file_role_v1_role_proto_rawDesc)))
	})
	return file_role_v1_role_proto_rawDescData
}

var file_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_role_v1_role_proto_goTypes = []any{
	(*CreateRoleReq)(nil),              // 0: role.v1.CreateRoleReq
	(*CreateRoleRes)(nil),              // 1: role.v1.CreateRoleRes
	(*UpdateRoleReq)(nil),              // 2: role.v1.UpdateRoleReq
	(*UpdateRoleRes)(nil),              // 3: role.v1.UpdateRoleRes
	(*DeleteRoleReq)(nil),              // 4: role.v1.DeleteRoleReq
	(*DeleteRoleRes)(nil),              // 5: role.v1.DeleteRoleRes
	(*GetRoleReq)(nil),                 // 6: role.v1.GetRoleReq
	(*GetRoleRes)(nil),                 // 7: role.v1.GetRoleRes
	(*ListRoleReq)(nil),                // 8: role.v1.ListRoleReq
	(*ListRoleRes)(nil),                // 9: role.v1.ListRoleRes
	(*GetRolePositionListReq)(nil),     // 10: role.v1.GetRolePositionListReq
	(*GetRolePositionListRes)(nil),     // 11: role.v1.GetRolePositionListRes
	(*PositionItem)(nil),               // 12: role.v1.PositionItem
	(*BatchAssignRolePositionReq)(nil), // 13: role.v1.BatchAssignRolePositionReq
	(*BatchAssignRolePositionRes)(nil), // 14: role.v1.BatchAssignRolePositionRes
	(*GetRolePositionIdsReq)(nil),      // 15: role.v1.GetRolePositionIdsReq
	(*GetRolePositionIdsRes)(nil),      // 16: role.v1.GetRolePositionIdsRes
}
var file_role_v1_role_proto_depIdxs = []int32{
	7,  // 0: role.v1.ListRoleRes.list:type_name -> role.v1.GetRoleRes
	12, // 1: role.v1.GetRolePositionListRes.list:type_name -> role.v1.PositionItem
	0,  // 2: role.v1.Role.CreateRole:input_type -> role.v1.CreateRoleReq
	2,  // 3: role.v1.Role.UpdateRole:input_type -> role.v1.UpdateRoleReq
	4,  // 4: role.v1.Role.DeleteRole:input_type -> role.v1.DeleteRoleReq
	6,  // 5: role.v1.Role.GetRole:input_type -> role.v1.GetRoleReq
	8,  // 6: role.v1.Role.ListRole:input_type -> role.v1.ListRoleReq
	10, // 7: role.v1.Role.GetRolePositionList:input_type -> role.v1.GetRolePositionListReq
	13, // 8: role.v1.Role.BatchAssignRolePosition:input_type -> role.v1.BatchAssignRolePositionReq
	15, // 9: role.v1.Role.GetRolePositionIds:input_type -> role.v1.GetRolePositionIdsReq
	1,  // 10: role.v1.Role.CreateRole:output_type -> role.v1.CreateRoleRes
	3,  // 11: role.v1.Role.UpdateRole:output_type -> role.v1.UpdateRoleRes
	5,  // 12: role.v1.Role.DeleteRole:output_type -> role.v1.DeleteRoleRes
	7,  // 13: role.v1.Role.GetRole:output_type -> role.v1.GetRoleRes
	9,  // 14: role.v1.Role.ListRole:output_type -> role.v1.ListRoleRes
	11, // 15: role.v1.Role.GetRolePositionList:output_type -> role.v1.GetRolePositionListRes
	14, // 16: role.v1.Role.BatchAssignRolePosition:output_type -> role.v1.BatchAssignRolePositionRes
	16, // 17: role.v1.Role.GetRolePositionIds:output_type -> role.v1.GetRolePositionIdsRes
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_role_v1_role_proto_init() }
func file_role_v1_role_proto_init() {
	if File_role_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_v1_role_proto_rawDesc), len(file_role_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_v1_role_proto_goTypes,
		DependencyIndexes: file_role_v1_role_proto_depIdxs,
		MessageInfos:      file_role_v1_role_proto_msgTypes,
	}.Build()
	File_role_v1_role_proto = out.File
	file_role_v1_role_proto_goTypes = nil
	file_role_v1_role_proto_depIdxs = nil
}
