// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package enum

import (
	"bbk/app/gateway/api/enum"
	v1 "bbk/app/system/api/enum/v1"
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	EnumRpcService v1.EnumClient
}

func NewV1() enum.IEnumV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("system")
	return &ControllerV1{
		v1.NewEnumClient(conn),
	}
}
