// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package permission

import (
	"freeroam/app/gateway/api/permission"
	oPermission "freeroam/app/org/api/permission/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	PermissionRpcService oPermission.PermissionClient
}

func NewV1() permission.IPermissionV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		PermissionRpcService: oPermission.NewPermissionClient(conn),
	}
}
