// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package permissions

import (
	"freeroam/app/gateway/api/permissions"
	oPermissions "freeroam/app/org/api/permissions/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	PermissionsRpcService oPermissions.PermissionsClient
}

func NewV1() permissions.IPermissionsV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		PermissionsRpcService: oPermissions.NewPermissionsClient(conn),
	}
}
