// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: user_member/v1/user_member.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserMember_GetList_FullMethodName = "/user_member.v1.UserMember/GetList"
	UserMember_Get_FullMethodName     = "/user_member.v1.UserMember/Get"
)

// UserMemberClient is the client API for UserMember service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMemberClient interface {
	// 获取列表
	GetList(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (*GetListRes, error)
	// 获取详情
	Get(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneRes, error)
}

type userMemberClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMemberClient(cc grpc.ClientConnInterface) UserMemberClient {
	return &userMemberClient{cc}
}

func (c *userMemberClient) GetList(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (*GetListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListRes)
	err := c.cc.Invoke(ctx, UserMember_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMemberClient) Get(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneRes)
	err := c.cc.Invoke(ctx, UserMember_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMemberServer is the server API for UserMember service.
// All implementations must embed UnimplementedUserMemberServer
// for forward compatibility.
type UserMemberServer interface {
	// 获取列表
	GetList(context.Context, *GetListReq) (*GetListRes, error)
	// 获取详情
	Get(context.Context, *GetOneReq) (*GetOneRes, error)
	mustEmbedUnimplementedUserMemberServer()
}

// UnimplementedUserMemberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserMemberServer struct{}

func (UnimplementedUserMemberServer) GetList(context.Context, *GetListReq) (*GetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedUserMemberServer) Get(context.Context, *GetOneReq) (*GetOneRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserMemberServer) mustEmbedUnimplementedUserMemberServer() {}
func (UnimplementedUserMemberServer) testEmbeddedByValue()                    {}

// UnsafeUserMemberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMemberServer will
// result in compilation errors.
type UnsafeUserMemberServer interface {
	mustEmbedUnimplementedUserMemberServer()
}

func RegisterUserMemberServer(s grpc.ServiceRegistrar, srv UserMemberServer) {
	// If the following call pancis, it indicates UnimplementedUserMemberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserMember_ServiceDesc, srv)
}

func _UserMember_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMemberServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserMember_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMemberServer).GetList(ctx, req.(*GetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMember_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMemberServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserMember_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMemberServer).Get(ctx, req.(*GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserMember_ServiceDesc is the grpc.ServiceDesc for UserMember service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserMember_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_member.v1.UserMember",
	HandlerType: (*UserMemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _UserMember_GetList_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserMember_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_member/v1/user_member.proto",
}
