// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: user_member/v1/user_member.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名，模糊搜索
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" dc:"用户名，模糊搜索"`
	// 姓名，模糊搜索
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"姓名，模糊搜索"`
	// 手机号
	Mobile string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty" dc:"手机号"`
	// 性别
	Gender *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty" dc:"性别"`
	// 状态
	Status *wrapperspb.Int64Value `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 分页号码
	// v:min:0#分页号码错误
	Page int32 `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty" dc:"分页号码" v:"min:0#分页号码错误"`
	// 分页数量，最大100
	// v:max:100#分页数量最大100条
	Limit         int32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty" dc:"分页数量，最大100" v:"max:100#分页数量最大100条"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_user_member_v1_user_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_member_v1_user_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_user_member_v1_user_member_proto_rawDescGZIP(), []int{0}
}

func (x *GetListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetListReq) GetGender() *wrapperspb.Int64Value {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *GetListReq) GetStatus() *wrapperspb.Int64Value {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据列表
	List []*GetListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"数据列表"`
	// 数据总数
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"数据总数"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes) Reset() {
	*x = GetListRes{}
	mi := &file_user_member_v1_user_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes) ProtoMessage() {}

func (x *GetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_member_v1_user_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes.ProtoReflect.Descriptor instead.
func (*GetListRes) Descriptor() ([]byte, []int) {
	return file_user_member_v1_user_member_proto_rawDescGZIP(), []int{1}
}

func (x *GetListRes) GetList() []*GetListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" dc:"用户名"`
	// 姓名
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 手机号
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty" dc:"手机号"`
	// 性别
	Gender int64 `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty" dc:"性别"`
	// 状态
	Status int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 创建时间
	CreateAt      string `protobuf:"bytes,7,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItem) Reset() {
	*x = GetListItem{}
	mi := &file_user_member_v1_user_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItem) ProtoMessage() {}

func (x *GetListItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_member_v1_user_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItem.ProtoReflect.Descriptor instead.
func (*GetListItem) Descriptor() ([]byte, []int) {
	return file_user_member_v1_user_member_proto_rawDescGZIP(), []int{2}
}

func (x *GetListItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetListItem) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListItem) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetListItem) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetListItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetListItem) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

type GetOneReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	// v:required|integer|min:1#用户ID不能为空|用户ID必须是整数|用户ID不能小于1
	UserId        int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID" v:"required|integer|min:1#用户ID不能为空|用户ID必须是整数|用户ID不能小于1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneReq) Reset() {
	*x = GetOneReq{}
	mi := &file_user_member_v1_user_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneReq) ProtoMessage() {}

func (x *GetOneReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_member_v1_user_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneReq.ProtoReflect.Descriptor instead.
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return file_user_member_v1_user_member_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOneRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" dc:"用户名"`
	// 姓名
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 手机号
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty" dc:"手机号"`
	// 性别
	Gender int64 `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty" dc:"性别"`
	// 状态
	Status int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 超级管理员
	Super         int64 `protobuf:"varint,7,opt,name=super,proto3" json:"super,omitempty" dc:"超级管理员"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRes) Reset() {
	*x = GetOneRes{}
	mi := &file_user_member_v1_user_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRes) ProtoMessage() {}

func (x *GetOneRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_member_v1_user_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRes.ProtoReflect.Descriptor instead.
func (*GetOneRes) Descriptor() ([]byte, []int) {
	return file_user_member_v1_user_member_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOneRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetOneRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOneRes) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetOneRes) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetOneRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOneRes) GetSuper() int64 {
	if x != nil {
		return x.Super
	}
	return 0
}

var File_user_member_v1_user_member_proto protoreflect.FileDescriptor

const file_user_member_v1_user_member_proto_rawDesc = "" +
	"\n" +
	" user_member/v1/user_member.proto\x12\x0euser_member.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\xe8\x01\n" +
	"\n" +
	"GetListReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x123\n" +
	"\x06gender\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06gender\x123\n" +
	"\x06status\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06status\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"S\n" +
	"\n" +
	"GetListRes\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.user_member.v1.GetListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb9\x01\n" +
	"\vGetListItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x03R\x06gender\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1a\n" +
	"\bcreateAt\x18\a \x01(\tR\bcreateAt\"#\n" +
	"\tGetOneReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\xb1\x01\n" +
	"\tGetOneRes\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x03R\x06gender\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x14\n" +
	"\x05super\x18\a \x01(\x03R\x05super2\x90\x01\n" +
	"\n" +
	"UserMember\x12C\n" +
	"\aGetList\x12\x1a.user_member.v1.GetListReq\x1a\x1a.user_member.v1.GetListRes\"\x00\x12=\n" +
	"\x03Get\x12\x19.user_member.v1.GetOneReq\x1a\x19.user_member.v1.GetOneRes\"\x00B\x16Z\x14./api/user_member/v1b\x06proto3"

var (
	file_user_member_v1_user_member_proto_rawDescOnce sync.Once
	file_user_member_v1_user_member_proto_rawDescData []byte
)

func file_user_member_v1_user_member_proto_rawDescGZIP() []byte {
	file_user_member_v1_user_member_proto_rawDescOnce.Do(func() {
		file_user_member_v1_user_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_member_v1_user_member_proto_rawDesc), len(file_user_member_v1_user_member_proto_rawDesc)))
	})
	return file_user_member_v1_user_member_proto_rawDescData
}

var file_user_member_v1_user_member_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_member_v1_user_member_proto_goTypes = []any{
	(*GetListReq)(nil),            // 0: user_member.v1.GetListReq
	(*GetListRes)(nil),            // 1: user_member.v1.GetListRes
	(*GetListItem)(nil),           // 2: user_member.v1.GetListItem
	(*GetOneReq)(nil),             // 3: user_member.v1.GetOneReq
	(*GetOneRes)(nil),             // 4: user_member.v1.GetOneRes
	(*wrapperspb.Int64Value)(nil), // 5: google.protobuf.Int64Value
}
var file_user_member_v1_user_member_proto_depIdxs = []int32{
	5, // 0: user_member.v1.GetListReq.gender:type_name -> google.protobuf.Int64Value
	5, // 1: user_member.v1.GetListReq.status:type_name -> google.protobuf.Int64Value
	2, // 2: user_member.v1.GetListRes.list:type_name -> user_member.v1.GetListItem
	0, // 3: user_member.v1.UserMember.GetList:input_type -> user_member.v1.GetListReq
	3, // 4: user_member.v1.UserMember.Get:input_type -> user_member.v1.GetOneReq
	1, // 5: user_member.v1.UserMember.GetList:output_type -> user_member.v1.GetListRes
	4, // 6: user_member.v1.UserMember.Get:output_type -> user_member.v1.GetOneRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_member_v1_user_member_proto_init() }
func file_user_member_v1_user_member_proto_init() {
	if File_user_member_v1_user_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_member_v1_user_member_proto_rawDesc), len(file_user_member_v1_user_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_member_v1_user_member_proto_goTypes,
		DependencyIndexes: file_user_member_v1_user_member_proto_depIdxs,
		MessageInfos:      file_user_member_v1_user_member_proto_msgTypes,
	}.Build()
	File_user_member_v1_user_member_proto = out.File
	file_user_member_v1_user_member_proto_goTypes = nil
	file_user_member_v1_user_member_proto_depIdxs = nil
}
