// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user_member

import (
	"freeroam/app/gateway/api/user_member"
	v1 "freeroam/app/org/api/user_member/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	UserMemberRpcService v1.UserMemberClient
}

func NewV1() user_member.IUserMemberV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		v1.NewUserMemberClient(conn),
	}
}
