// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package org

import (
	"freeroam/app/gateway/api/org"
	oOrg "freeroam/app/org/api/org/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	OrgRpcService oOrg.OrgClient
}

func NewV1() org.IOrgV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		OrgRpcService: oOrg.NewOrgClient(conn),
	}
}
