// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package org

import (
	"bbk/app/gateway/api/org"
	v1 "bbk/app/org/api/org/v1"
	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	OrgRpcService v1.OrgClient
}

func NewV1() org.IOrgV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		v1.NewOrgClient(conn),
	}
}
