// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: admin_login/v1/admin_login.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminLogin_Login_FullMethodName = "/admin_login.v1.AdminLogin/Login"
)

// AdminLoginClient is the client API for AdminLogin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminLoginClient interface {
	// 获取成员详情
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
}

type adminLoginClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminLoginClient(cc grpc.ClientConnInterface) AdminLoginClient {
	return &adminLoginClient{cc}
}

func (c *adminLoginClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, AdminLogin_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminLoginServer is the server API for AdminLogin service.
// All implementations must embed UnimplementedAdminLoginServer
// for forward compatibility.
type AdminLoginServer interface {
	// 获取成员详情
	Login(context.Context, *LoginReq) (*LoginRes, error)
	mustEmbedUnimplementedAdminLoginServer()
}

// UnimplementedAdminLoginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminLoginServer struct{}

func (UnimplementedAdminLoginServer) Login(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAdminLoginServer) mustEmbedUnimplementedAdminLoginServer() {}
func (UnimplementedAdminLoginServer) testEmbeddedByValue()                    {}

// UnsafeAdminLoginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminLoginServer will
// result in compilation errors.
type UnsafeAdminLoginServer interface {
	mustEmbedUnimplementedAdminLoginServer()
}

func RegisterAdminLoginServer(s grpc.ServiceRegistrar, srv AdminLoginServer) {
	// If the following call pancis, it indicates UnimplementedAdminLoginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminLogin_ServiceDesc, srv)
}

func _AdminLogin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminLoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminLogin_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminLoginServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminLogin_ServiceDesc is the grpc.ServiceDesc for AdminLogin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminLogin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_login.v1.AdminLogin",
	HandlerType: (*AdminLoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AdminLogin_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_login/v1/admin_login.proto",
}
