// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: admin_login/v1/admin_login.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_admin_login_v1_admin_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_login_v1_admin_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_admin_login_v1_admin_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Token                string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ForceExpiresTimeUnix int64                  `protobuf:"varint,4,opt,name=forceExpiresTimeUnix,proto3" json:"forceExpiresTimeUnix,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_admin_login_v1_admin_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_login_v1_admin_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_admin_login_v1_admin_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginRes) GetForceExpiresTimeUnix() int64 {
	if x != nil {
		return x.ForceExpiresTimeUnix
	}
	return 0
}

var File_admin_login_v1_admin_login_proto protoreflect.FileDescriptor

const file_admin_login_v1_admin_login_proto_rawDesc = "" +
	"\n" +
	" admin_login/v1/admin_login.proto\x12\x0eadmin_login.v1\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x80\x01\n" +
	"\bLoginRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x122\n" +
	"\x14forceExpiresTimeUnix\x18\x04 \x01(\x03R\x14forceExpiresTimeUnix2K\n" +
	"\n" +
	"AdminLogin\x12=\n" +
	"\x05Login\x12\x18.admin_login.v1.LoginReq\x1a\x18.admin_login.v1.LoginRes\"\x00B\x17Z\x15./api/admin_member/v1b\x06proto3"

var (
	file_admin_login_v1_admin_login_proto_rawDescOnce sync.Once
	file_admin_login_v1_admin_login_proto_rawDescData []byte
)

func file_admin_login_v1_admin_login_proto_rawDescGZIP() []byte {
	file_admin_login_v1_admin_login_proto_rawDescOnce.Do(func() {
		file_admin_login_v1_admin_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_login_v1_admin_login_proto_rawDesc), len(file_admin_login_v1_admin_login_proto_rawDesc)))
	})
	return file_admin_login_v1_admin_login_proto_rawDescData
}

var file_admin_login_v1_admin_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_admin_login_v1_admin_login_proto_goTypes = []any{
	(*LoginReq)(nil), // 0: admin_login.v1.LoginReq
	(*LoginRes)(nil), // 1: admin_login.v1.LoginRes
}
var file_admin_login_v1_admin_login_proto_depIdxs = []int32{
	0, // 0: admin_login.v1.AdminLogin.Login:input_type -> admin_login.v1.LoginReq
	1, // 1: admin_login.v1.AdminLogin.Login:output_type -> admin_login.v1.LoginRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_login_v1_admin_login_proto_init() }
func file_admin_login_v1_admin_login_proto_init() {
	if File_admin_login_v1_admin_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_login_v1_admin_login_proto_rawDesc), len(file_admin_login_v1_admin_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_login_v1_admin_login_proto_goTypes,
		DependencyIndexes: file_admin_login_v1_admin_login_proto_depIdxs,
		MessageInfos:      file_admin_login_v1_admin_login_proto_msgTypes,
	}.Build()
	File_admin_login_v1_admin_login_proto = out.File
	file_admin_login_v1_admin_login_proto_goTypes = nil
	file_admin_login_v1_admin_login_proto_depIdxs = nil
}
