// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: admin_member/v1/admin_member.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	// v:required|integer|min:1#用户ID不能为空|用户ID必须是整数|用户ID不能小于1
	UserId        int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID" v:"required|integer|min:1#用户ID不能为空|用户ID必须是整数|用户ID不能小于1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_admin_member_v1_admin_member_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 状态
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 用户名
	Username      string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty" dc:"用户名"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_admin_member_v1_admin_member_proto_rawDescGZIP(), []int{1}
}

func (x *GetRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	// v:integer#userId必须是整数
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID" v:"integer#userId必须是整数"`
	// 【名称|用户名】模糊搜索
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"【名称|用户名】模糊搜索"`
	// 状态，见枚举
	// v:in:0,1,2#成员状态参数不正确
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty" dc:"状态，见枚举" v:"in:0,1,2#成员状态参数不正确"`
	// 分页号码
	// v:min:0#分页号码错误
	Page int32 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty" dc:"分页号码" v:"min:0#分页号码错误"`
	// 分页数量，最大100
	// v:max:100#分页数量最大100条
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty" dc:"分页数量，最大100" v:"max:100#分页数量最大100条"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_admin_member_v1_admin_member_proto_rawDescGZIP(), []int{2}
}

func (x *GetListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *GetListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据列表
	List []*GetListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"数据列表"`
	// 数据总数
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"数据总数"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes) Reset() {
	*x = GetListRes{}
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes) ProtoMessage() {}

func (x *GetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes.ProtoReflect.Descriptor instead.
func (*GetListRes) Descriptor() ([]byte, []int) {
	return file_admin_member_v1_admin_member_proto_rawDescGZIP(), []int{3}
}

func (x *GetListRes) GetList() []*GetListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty" dc:"用户ID"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 状态
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 最后登陆时间
	LastTime string `protobuf:"bytes,4,opt,name=lastTime,proto3" json:"lastTime,omitempty" dc:"最后登陆时间"`
	// 最后登陆IP
	LastIp string `protobuf:"bytes,5,opt,name=lastIp,proto3" json:"lastIp,omitempty" dc:"最后登陆IP"`
	// 创建时间
	CreateAt      string `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItem) Reset() {
	*x = GetListItem{}
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItem) ProtoMessage() {}

func (x *GetListItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_member_v1_admin_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItem.ProtoReflect.Descriptor instead.
func (*GetListItem) Descriptor() ([]byte, []int) {
	return file_admin_member_v1_admin_member_proto_rawDescGZIP(), []int{4}
}

func (x *GetListItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetListItem) GetLastTime() string {
	if x != nil {
		return x.LastTime
	}
	return ""
}

func (x *GetListItem) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *GetListItem) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

var File_admin_member_v1_admin_member_proto protoreflect.FileDescriptor

const file_admin_member_v1_admin_member_proto_rawDesc = "" +
	"\n" +
	"\"admin_member/v1/admin_member.proto\x12\x0fadmin_member.v1\" \n" +
	"\x06GetReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"h\n" +
	"\x06GetRes\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"\x8a\x01\n" +
	"\n" +
	"GetListReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\t\n" +
	"\a_status\"T\n" +
	"\n" +
	"GetListRes\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.admin_member.v1.GetListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa1\x01\n" +
	"\vGetListItem\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\blastTime\x18\x04 \x01(\tR\blastTime\x12\x16\n" +
	"\x06lastIp\x18\x05 \x01(\tR\x06lastIp\x12\x1a\n" +
	"\bcreateAt\x18\x06 \x01(\tR\bcreateAt2\x8f\x01\n" +
	"\vAdminMember\x129\n" +
	"\x03Get\x12\x17.admin_member.v1.GetReq\x1a\x17.admin_member.v1.GetRes\"\x00\x12E\n" +
	"\aGetList\x12\x1b.admin_member.v1.GetListReq\x1a\x1b.admin_member.v1.GetListRes\"\x00B\x17Z\x15./api/admin_member/v1b\x06proto3"

var (
	file_admin_member_v1_admin_member_proto_rawDescOnce sync.Once
	file_admin_member_v1_admin_member_proto_rawDescData []byte
)

func file_admin_member_v1_admin_member_proto_rawDescGZIP() []byte {
	file_admin_member_v1_admin_member_proto_rawDescOnce.Do(func() {
		file_admin_member_v1_admin_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_member_v1_admin_member_proto_rawDesc), len(file_admin_member_v1_admin_member_proto_rawDesc)))
	})
	return file_admin_member_v1_admin_member_proto_rawDescData
}

var file_admin_member_v1_admin_member_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_member_v1_admin_member_proto_goTypes = []any{
	(*GetReq)(nil),      // 0: admin_member.v1.GetReq
	(*GetRes)(nil),      // 1: admin_member.v1.GetRes
	(*GetListReq)(nil),  // 2: admin_member.v1.GetListReq
	(*GetListRes)(nil),  // 3: admin_member.v1.GetListRes
	(*GetListItem)(nil), // 4: admin_member.v1.GetListItem
}
var file_admin_member_v1_admin_member_proto_depIdxs = []int32{
	4, // 0: admin_member.v1.GetListRes.list:type_name -> admin_member.v1.GetListItem
	0, // 1: admin_member.v1.AdminMember.Get:input_type -> admin_member.v1.GetReq
	2, // 2: admin_member.v1.AdminMember.GetList:input_type -> admin_member.v1.GetListReq
	1, // 3: admin_member.v1.AdminMember.Get:output_type -> admin_member.v1.GetRes
	3, // 4: admin_member.v1.AdminMember.GetList:output_type -> admin_member.v1.GetListRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admin_member_v1_admin_member_proto_init() }
func file_admin_member_v1_admin_member_proto_init() {
	if File_admin_member_v1_admin_member_proto != nil {
		return
	}
	file_admin_member_v1_admin_member_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_member_v1_admin_member_proto_rawDesc), len(file_admin_member_v1_admin_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_member_v1_admin_member_proto_goTypes,
		DependencyIndexes: file_admin_member_v1_admin_member_proto_depIdxs,
		MessageInfos:      file_admin_member_v1_admin_member_proto_msgTypes,
	}.Build()
	File_admin_member_v1_admin_member_proto = out.File
	file_admin_member_v1_admin_member_proto_goTypes = nil
	file_admin_member_v1_admin_member_proto_depIdxs = nil
}
