// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0--rc1
// source: enum/v1/enum.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Enum_GetEnumLists_FullMethodName = "/enum.v1.Enum/GetEnumLists"
)

// EnumClient is the client API for Enum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnumClient interface {
	GetEnumLists(ctx context.Context, in *GetEnumListsReq, opts ...grpc.CallOption) (*EnumListsRes, error)
}

type enumClient struct {
	cc grpc.ClientConnInterface
}

func NewEnumClient(cc grpc.ClientConnInterface) EnumClient {
	return &enumClient{cc}
}

func (c *enumClient) GetEnumLists(ctx context.Context, in *GetEnumListsReq, opts ...grpc.CallOption) (*EnumListsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumListsRes)
	err := c.cc.Invoke(ctx, Enum_GetEnumLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnumServer is the server API for Enum service.
// All implementations must embed UnimplementedEnumServer
// for forward compatibility.
type EnumServer interface {
	GetEnumLists(context.Context, *GetEnumListsReq) (*EnumListsRes, error)
	mustEmbedUnimplementedEnumServer()
}

// UnimplementedEnumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnumServer struct{}

func (UnimplementedEnumServer) GetEnumLists(context.Context, *GetEnumListsReq) (*EnumListsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnumLists not implemented")
}
func (UnimplementedEnumServer) mustEmbedUnimplementedEnumServer() {}
func (UnimplementedEnumServer) testEmbeddedByValue()              {}

// UnsafeEnumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnumServer will
// result in compilation errors.
type UnsafeEnumServer interface {
	mustEmbedUnimplementedEnumServer()
}

func RegisterEnumServer(s grpc.ServiceRegistrar, srv EnumServer) {
	// If the following call pancis, it indicates UnimplementedEnumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enum_ServiceDesc, srv)
}

func _Enum_GetEnumLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnumListsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServer).GetEnumLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enum_GetEnumLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServer).GetEnumLists(ctx, req.(*GetEnumListsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Enum_ServiceDesc is the grpc.ServiceDesc for Enum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enum.v1.Enum",
	HandlerType: (*EnumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnumLists",
			Handler:    _Enum_GetEnumLists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enum/v1/enum.proto",
}
