// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: enum/v1/enum.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Enum_GetByTypeAndCode_FullMethodName = "/enum.v1.Enum/GetByTypeAndCode"
	Enum_GetByType_FullMethodName        = "/enum.v1.Enum/GetByType"
)

// EnumClient is the client API for Enum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnumClient interface {
	// 根据枚举类型和code 获取一个枚举
	GetByTypeAndCode(ctx context.Context, in *GetByTypeAndCodeReq, opts ...grpc.CallOption) (*GetByTypeAndCodeRes, error)
	// 根据枚举类型数组 获取多个枚举
	GetByType(ctx context.Context, in *GetByTypeReq, opts ...grpc.CallOption) (*GetByTypeRes, error)
}

type enumClient struct {
	cc grpc.ClientConnInterface
}

func NewEnumClient(cc grpc.ClientConnInterface) EnumClient {
	return &enumClient{cc}
}

func (c *enumClient) GetByTypeAndCode(ctx context.Context, in *GetByTypeAndCodeReq, opts ...grpc.CallOption) (*GetByTypeAndCodeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByTypeAndCodeRes)
	err := c.cc.Invoke(ctx, Enum_GetByTypeAndCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enumClient) GetByType(ctx context.Context, in *GetByTypeReq, opts ...grpc.CallOption) (*GetByTypeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByTypeRes)
	err := c.cc.Invoke(ctx, Enum_GetByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnumServer is the server API for Enum service.
// All implementations must embed UnimplementedEnumServer
// for forward compatibility.
type EnumServer interface {
	// 根据枚举类型和code 获取一个枚举
	GetByTypeAndCode(context.Context, *GetByTypeAndCodeReq) (*GetByTypeAndCodeRes, error)
	// 根据枚举类型数组 获取多个枚举
	GetByType(context.Context, *GetByTypeReq) (*GetByTypeRes, error)
	mustEmbedUnimplementedEnumServer()
}

// UnimplementedEnumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnumServer struct{}

func (UnimplementedEnumServer) GetByTypeAndCode(context.Context, *GetByTypeAndCodeReq) (*GetByTypeAndCodeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByTypeAndCode not implemented")
}
func (UnimplementedEnumServer) GetByType(context.Context, *GetByTypeReq) (*GetByTypeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByType not implemented")
}
func (UnimplementedEnumServer) mustEmbedUnimplementedEnumServer() {}
func (UnimplementedEnumServer) testEmbeddedByValue()              {}

// UnsafeEnumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnumServer will
// result in compilation errors.
type UnsafeEnumServer interface {
	mustEmbedUnimplementedEnumServer()
}

func RegisterEnumServer(s grpc.ServiceRegistrar, srv EnumServer) {
	// If the following call panics, it indicates UnimplementedEnumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Enum_ServiceDesc, srv)
}

func _Enum_GetByTypeAndCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTypeAndCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServer).GetByTypeAndCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enum_GetByTypeAndCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServer).GetByTypeAndCode(ctx, req.(*GetByTypeAndCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Enum_GetByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnumServer).GetByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Enum_GetByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnumServer).GetByType(ctx, req.(*GetByTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Enum_ServiceDesc is the grpc.ServiceDesc for Enum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Enum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enum.v1.Enum",
	HandlerType: (*EnumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByTypeAndCode",
			Handler:    _Enum_GetByTypeAndCode_Handler,
		},
		{
			MethodName: "GetByType",
			Handler:    _Enum_GetByType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enum/v1/enum.proto",
}
