// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: enum/v1/enum.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEnumListsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GetEnumListsReqItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnumListsReq) Reset() {
	*x = GetEnumListsReq{}
	mi := &file_enum_v1_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnumListsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnumListsReq) ProtoMessage() {}

func (x *GetEnumListsReq) ProtoReflect() protoreflect.Message {
	mi := &file_enum_v1_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnumListsReq.ProtoReflect.Descriptor instead.
func (*GetEnumListsReq) Descriptor() ([]byte, []int) {
	return file_enum_v1_enum_proto_rawDescGZIP(), []int{0}
}

func (x *GetEnumListsReq) GetList() []*GetEnumListsReqItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetEnumListsReqItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 枚举编码
	// v:required#枚举编码不能为空
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty" dc:"枚举编码" v:"required#枚举编码不能为空"`
	// 表名
	// v:required#表名不能为空
	TableName string `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty" dc:"表名" v:"required#表名不能为空"`
	// 模块名
	Module        string `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty" dc:"模块名"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnumListsReqItem) Reset() {
	*x = GetEnumListsReqItem{}
	mi := &file_enum_v1_enum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnumListsReqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnumListsReqItem) ProtoMessage() {}

func (x *GetEnumListsReqItem) ProtoReflect() protoreflect.Message {
	mi := &file_enum_v1_enum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnumListsReqItem.ProtoReflect.Descriptor instead.
func (*GetEnumListsReqItem) Descriptor() ([]byte, []int) {
	return file_enum_v1_enum_proto_rawDescGZIP(), []int{1}
}

func (x *GetEnumListsReqItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetEnumListsReqItem) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *GetEnumListsReqItem) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type EnumListsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*EnumListsItem       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumListsRes) Reset() {
	*x = EnumListsRes{}
	mi := &file_enum_v1_enum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumListsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumListsRes) ProtoMessage() {}

func (x *EnumListsRes) ProtoReflect() protoreflect.Message {
	mi := &file_enum_v1_enum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumListsRes.ProtoReflect.Descriptor instead.
func (*EnumListsRes) Descriptor() ([]byte, []int) {
	return file_enum_v1_enum_proto_rawDescGZIP(), []int{2}
}

func (x *EnumListsRes) GetList() []*EnumListsItem {
	if x != nil {
		return x.List
	}
	return nil
}

type EnumListsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	List          []*EnumListItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumListsItem) Reset() {
	*x = EnumListsItem{}
	mi := &file_enum_v1_enum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumListsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumListsItem) ProtoMessage() {}

func (x *EnumListsItem) ProtoReflect() protoreflect.Message {
	mi := &file_enum_v1_enum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumListsItem.ProtoReflect.Descriptor instead.
func (*EnumListsItem) Descriptor() ([]byte, []int) {
	return file_enum_v1_enum_proto_rawDescGZIP(), []int{3}
}

func (x *EnumListsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumListsItem) GetList() []*EnumListItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 枚举元素
type EnumListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 枚举值
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty" dc:"枚举值"`
	// 枚举值描述
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"枚举值描述"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumListItem) Reset() {
	*x = EnumListItem{}
	mi := &file_enum_v1_enum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumListItem) ProtoMessage() {}

func (x *EnumListItem) ProtoReflect() protoreflect.Message {
	mi := &file_enum_v1_enum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumListItem.ProtoReflect.Descriptor instead.
func (*EnumListItem) Descriptor() ([]byte, []int) {
	return file_enum_v1_enum_proto_rawDescGZIP(), []int{4}
}

func (x *EnumListItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnumListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_enum_v1_enum_proto protoreflect.FileDescriptor

const file_enum_v1_enum_proto_rawDesc = "" +
	"\n" +
	"\x12enum/v1/enum.proto\x12\aenum.v1\"C\n" +
	"\x0fGetEnumListsReq\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.enum.v1.GetEnumListsReqItemR\x04list\"_\n" +
	"\x13GetEnumListsReqItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\ttableName\x18\x02 \x01(\tR\ttableName\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\":\n" +
	"\fEnumListsRes\x12*\n" +
	"\x04list\x18\x01 \x03(\v2\x16.enum.v1.EnumListsItemR\x04list\"N\n" +
	"\rEnumListsItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04list\x18\x02 \x03(\v2\x15.enum.v1.EnumListItemR\x04list\"8\n" +
	"\fEnumListItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2G\n" +
	"\x04Enum\x12?\n" +
	"\fGetEnumLists\x12\x18.enum.v1.GetEnumListsReq\x1a\x15.enum.v1.EnumListsResB\x0fZ\r./api/enum/v1b\x06proto3"

var (
	file_enum_v1_enum_proto_rawDescOnce sync.Once
	file_enum_v1_enum_proto_rawDescData []byte
)

func file_enum_v1_enum_proto_rawDescGZIP() []byte {
	file_enum_v1_enum_proto_rawDescOnce.Do(func() {
		file_enum_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_v1_enum_proto_rawDesc), len(file_enum_v1_enum_proto_rawDesc)))
	})
	return file_enum_v1_enum_proto_rawDescData
}

var file_enum_v1_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_enum_v1_enum_proto_goTypes = []any{
	(*GetEnumListsReq)(nil),     // 0: enum.v1.GetEnumListsReq
	(*GetEnumListsReqItem)(nil), // 1: enum.v1.GetEnumListsReqItem
	(*EnumListsRes)(nil),        // 2: enum.v1.EnumListsRes
	(*EnumListsItem)(nil),       // 3: enum.v1.EnumListsItem
	(*EnumListItem)(nil),        // 4: enum.v1.EnumListItem
}
var file_enum_v1_enum_proto_depIdxs = []int32{
	1, // 0: enum.v1.GetEnumListsReq.list:type_name -> enum.v1.GetEnumListsReqItem
	3, // 1: enum.v1.EnumListsRes.list:type_name -> enum.v1.EnumListsItem
	4, // 2: enum.v1.EnumListsItem.list:type_name -> enum.v1.EnumListItem
	0, // 3: enum.v1.Enum.GetEnumLists:input_type -> enum.v1.GetEnumListsReq
	2, // 4: enum.v1.Enum.GetEnumLists:output_type -> enum.v1.EnumListsRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_enum_v1_enum_proto_init() }
func file_enum_v1_enum_proto_init() {
	if File_enum_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_v1_enum_proto_rawDesc), len(file_enum_v1_enum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enum_v1_enum_proto_goTypes,
		DependencyIndexes: file_enum_v1_enum_proto_depIdxs,
		MessageInfos:      file_enum_v1_enum_proto_msgTypes,
	}.Build()
	File_enum_v1_enum_proto = out.File
	file_enum_v1_enum_proto_goTypes = nil
	file_enum_v1_enum_proto_depIdxs = nil
}
