// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: position/v1/position.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 职务列表请求
type ListPositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" dc:"页码" v:"min:1#页码必须大于0"` // v:min:1#页码必须大于0
	// 每页数量
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量" v:"min:1|max:200#每页数量必须大于0|每页数量不能超过200"` // v:min:1|max:200#每页数量必须大于0|每页数量不能超过200
	// 职务名称模糊
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty" dc:"职务名称模糊"`
	// 状态:position_status
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status" v:"required|enum:position_status#状态不能为空"` // v:required|enum:position_status#状态不能为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionReq) Reset() {
	*x = ListPositionReq{}
	mi := &file_position_v1_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionReq) ProtoMessage() {}

func (x *ListPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionReq.ProtoReflect.Descriptor instead.
func (*ListPositionReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{0}
}

func (x *ListPositionReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPositionReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPositionReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListPositionReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 职务列表项
type PositionListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID"`
	// 职务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"职务名称"`
	// 状态:position_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status"`
	// 数据权限:position_data_scope
	DataScope string `protobuf:"bytes,4,opt,name=dataScope,proto3" json:"dataScope,omitempty" dc:"数据权限:position_data_scope"`
	// 关联的组织ID数组
	OrgIds []int64 `protobuf:"varint,5,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty" dc:"关联的组织ID数组"`
	// 关联的角色ID数组
	RoleIds []int64 `protobuf:"varint,6,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty" dc:"关联的角色ID数组"`
	// 创建时间
	CreateAt      int64 `protobuf:"varint,7,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionListItem) Reset() {
	*x = PositionListItem{}
	mi := &file_position_v1_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionListItem) ProtoMessage() {}

func (x *PositionListItem) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionListItem.ProtoReflect.Descriptor instead.
func (*PositionListItem) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{1}
}

func (x *PositionListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PositionListItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PositionListItem) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *PositionListItem) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *PositionListItem) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *PositionListItem) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

// 职务列表响应
type ListPositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务列表
	List []*PositionListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"职务列表"`
	// 总数
	Total int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"总数"`
	// 页码
	Page int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty" dc:"页码"`
	// 每页数量
	PageSize      int64 `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty" dc:"每页数量"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionRes) Reset() {
	*x = ListPositionRes{}
	mi := &file_position_v1_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionRes) ProtoMessage() {}

func (x *ListPositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionRes.ProtoReflect.Descriptor instead.
func (*ListPositionRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{2}
}

func (x *ListPositionRes) GetList() []*PositionListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPositionRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPositionRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPositionRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取职务详情请求
type GetPositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID" v:"required|min:1#职务ID不能为空|职务ID必须大于0"` // v:required|min:1#职务ID不能为空|职务ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionReq) Reset() {
	*x = GetPositionReq{}
	mi := &file_position_v1_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionReq) ProtoMessage() {}

func (x *GetPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionReq.ProtoReflect.Descriptor instead.
func (*GetPositionReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{3}
}

func (x *GetPositionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取职务详情响应
type GetPositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID"`
	// 职务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"职务名称"`
	// 状态:position_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status"`
	// 数据权限:position_data_scope
	DataScope string `protobuf:"bytes,4,opt,name=dataScope,proto3" json:"dataScope,omitempty" dc:"数据权限:position_data_scope"`
	// 关联的组织ID数组
	OrgIds []int64 `protobuf:"varint,5,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty" dc:"关联的组织ID数组"`
	// 关联的角色ID数组
	RoleIds []int64 `protobuf:"varint,6,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty" dc:"关联的角色ID数组"`
	// 创建时间
	CreateAt int64 `protobuf:"varint,7,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	// 更新时间
	UpdateAt      int64 `protobuf:"varint,8,opt,name=updateAt,proto3" json:"updateAt,omitempty" dc:"更新时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRes) Reset() {
	*x = GetPositionRes{}
	mi := &file_position_v1_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRes) ProtoMessage() {}

func (x *GetPositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRes.ProtoReflect.Descriptor instead.
func (*GetPositionRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{4}
}

func (x *GetPositionRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPositionRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPositionRes) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPositionRes) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *GetPositionRes) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *GetPositionRes) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *GetPositionRes) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *GetPositionRes) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// 新建职务请求
type CreatePositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" dc:"职务名称" v:"required|length:1,20#职务名称不能为空|职务名称长度必须在1-20之间"` // v:required|length:1,20#职务名称不能为空|职务名称长度必须在1-20之间
	// 状态:position_status
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status" v:"required|enum:position_status#状态不能为空"` // v:required|enum:position_status#状态不能为空
	// 数据权限:position_data_scope
	DataScope string `protobuf:"bytes,3,opt,name=dataScope,proto3" json:"dataScope,omitempty" dc:"数据权限:position_data_scope" v:"required|enum:position_data_scope#数据权限不能为空"` // v:required|enum:position_data_scope#数据权限不能为空
	// 关联的组织ID数组
	OrgIds []int64 `protobuf:"varint,4,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty" dc:"关联的组织ID数组"`
	// 关联的角色ID数组
	RoleIds       []int64 `protobuf:"varint,5,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty" dc:"关联的角色ID数组"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionReq) Reset() {
	*x = CreatePositionReq{}
	mi := &file_position_v1_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionReq) ProtoMessage() {}

func (x *CreatePositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionReq.ProtoReflect.Descriptor instead.
func (*CreatePositionReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePositionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePositionReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePositionReq) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *CreatePositionReq) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *CreatePositionReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 新建职务响应
type CreatePositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionRes) Reset() {
	*x = CreatePositionRes{}
	mi := &file_position_v1_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionRes) ProtoMessage() {}

func (x *CreatePositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionRes.ProtoReflect.Descriptor instead.
func (*CreatePositionRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePositionRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 编辑职务请求
type UpdatePositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID" v:"required|min:1#职务ID不能为空|职务ID必须大于0"` // v:required|min:1#职务ID不能为空|职务ID必须大于0
	// 职务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"职务名称" v:"length:1,20#职务名称长度必须在1-20之间"` // v:length:1,20#职务名称长度必须在1-20之间
	// 状态:position_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status" v:"required|enum:position_status#状态不能为空"` // v:required|enum:position_status#状态不能为空
	// 数据权限:position_data_scope
	DataScope string `protobuf:"bytes,4,opt,name=dataScope,proto3" json:"dataScope,omitempty" dc:"数据权限:position_data_scope" v:"required|enum:position_data_scope#数据权限不能为空"` // v:required|enum:position_data_scope#数据权限不能为空
	// 关联的组织ID数组
	OrgIds []int64 `protobuf:"varint,5,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty" dc:"关联的组织ID数组"`
	// 关联的角色ID数组
	RoleIds       []int64 `protobuf:"varint,6,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty" dc:"关联的角色ID数组"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionReq) Reset() {
	*x = UpdatePositionReq{}
	mi := &file_position_v1_position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionReq) ProtoMessage() {}

func (x *UpdatePositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionReq.ProtoReflect.Descriptor instead.
func (*UpdatePositionReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePositionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePositionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePositionReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePositionReq) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *UpdatePositionReq) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *UpdatePositionReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// 编辑职务响应
type UpdatePositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRes) Reset() {
	*x = UpdatePositionRes{}
	mi := &file_position_v1_position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRes) ProtoMessage() {}

func (x *UpdatePositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRes.ProtoReflect.Descriptor instead.
func (*UpdatePositionRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePositionRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 删除职务请求
type DeletePositionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID" v:"required|min:1#职务ID不能为空|职务ID必须大于0"` // v:required|min:1#职务ID不能为空|职务ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionReq) Reset() {
	*x = DeletePositionReq{}
	mi := &file_position_v1_position_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionReq) ProtoMessage() {}

func (x *DeletePositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionReq.ProtoReflect.Descriptor instead.
func (*DeletePositionReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePositionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除职务响应
type DeletePositionRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePositionRes) Reset() {
	*x = DeletePositionRes{}
	mi := &file_position_v1_position_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePositionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePositionRes) ProtoMessage() {}

func (x *DeletePositionRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePositionRes.ProtoReflect.Descriptor instead.
func (*DeletePositionRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePositionRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 按组织获取可选职务集合请求
type GetPositionOptionsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID列表(逗号分隔)
	OrgIds []int64 `protobuf:"varint,1,rep,packed,name=orgIds,proto3" json:"orgIds,omitempty" dc:"组织ID列表(逗号分隔)" v:"required#组织ID不能为空"` // v:required#组织ID不能为空
	// 状态过滤,默认仅返回启用
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty" dc:"状态过滤,默认仅返回启用" v:"required|enum:position_status#状态不能为空"` // v:required|enum:position_status#状态不能为空
	// 职务名称模糊
	Keyword       string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty" dc:"职务名称模糊"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionOptionsReq) Reset() {
	*x = GetPositionOptionsReq{}
	mi := &file_position_v1_position_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionOptionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionOptionsReq) ProtoMessage() {}

func (x *GetPositionOptionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionOptionsReq.ProtoReflect.Descriptor instead.
func (*GetPositionOptionsReq) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{11}
}

func (x *GetPositionOptionsReq) GetOrgIds() []int64 {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

func (x *GetPositionOptionsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPositionOptionsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 职务选项
type PositionOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"职务ID"`
	// 职务名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"职务名称"`
	// 状态:position_status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" dc:"状态:position_status"`
	// 数据权限:position_data_scope
	DataScope     string `protobuf:"bytes,4,opt,name=dataScope,proto3" json:"dataScope,omitempty" dc:"数据权限:position_data_scope"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionOption) Reset() {
	*x = PositionOption{}
	mi := &file_position_v1_position_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionOption) ProtoMessage() {}

func (x *PositionOption) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionOption.ProtoReflect.Descriptor instead.
func (*PositionOption) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{12}
}

func (x *PositionOption) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PositionOption) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PositionOption) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

// 按组织获取可选职务集合响应
type GetPositionOptionsRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 职务选项列表
	List          []*PositionOption `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"职务选项列表"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionOptionsRes) Reset() {
	*x = GetPositionOptionsRes{}
	mi := &file_position_v1_position_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionOptionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionOptionsRes) ProtoMessage() {}

func (x *GetPositionOptionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_v1_position_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionOptionsRes.ProtoReflect.Descriptor instead.
func (*GetPositionOptionsRes) Descriptor() ([]byte, []int) {
	return file_position_v1_position_proto_rawDescGZIP(), []int{13}
}

func (x *GetPositionOptionsRes) GetList() []*PositionOption {
	if x != nil {
		return x.List
	}
	return nil
}

var File_position_v1_position_proto protoreflect.FileDescriptor

const file_position_v1_position_proto_rawDesc = "" +
	"\n" +
	"\x1aposition/v1/position.proto\x12\vposition.v1\"s\n" +
	"\x0fListPositionReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xba\x01\n" +
	"\x10PositionListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tdataScope\x18\x04 \x01(\tR\tdataScope\x12\x16\n" +
	"\x06orgIds\x18\x05 \x03(\x03R\x06orgIds\x12\x18\n" +
	"\aroleIds\x18\x06 \x03(\x03R\aroleIds\x12\x1a\n" +
	"\bcreateAt\x18\a \x01(\x03R\bcreateAt\"\x8a\x01\n" +
	"\x0fListPositionRes\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.position.v1.PositionListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\" \n" +
	"\x0eGetPositionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd4\x01\n" +
	"\x0eGetPositionRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tdataScope\x18\x04 \x01(\tR\tdataScope\x12\x16\n" +
	"\x06orgIds\x18\x05 \x03(\x03R\x06orgIds\x12\x18\n" +
	"\aroleIds\x18\x06 \x03(\x03R\aroleIds\x12\x1a\n" +
	"\bcreateAt\x18\a \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\b \x01(\x03R\bupdateAt\"\x8f\x01\n" +
	"\x11CreatePositionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\tdataScope\x18\x03 \x01(\tR\tdataScope\x12\x16\n" +
	"\x06orgIds\x18\x04 \x03(\x03R\x06orgIds\x12\x18\n" +
	"\aroleIds\x18\x05 \x03(\x03R\aroleIds\"#\n" +
	"\x11CreatePositionRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9f\x01\n" +
	"\x11UpdatePositionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tdataScope\x18\x04 \x01(\tR\tdataScope\x12\x16\n" +
	"\x06orgIds\x18\x05 \x03(\x03R\x06orgIds\x12\x18\n" +
	"\aroleIds\x18\x06 \x03(\x03R\aroleIds\"-\n" +
	"\x11UpdatePositionRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11DeletePositionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x11DeletePositionRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x15GetPositionOptionsReq\x12\x16\n" +
	"\x06orgIds\x18\x01 \x03(\x03R\x06orgIds\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\"j\n" +
	"\x0ePositionOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tdataScope\x18\x04 \x01(\tR\tdataScope\"H\n" +
	"\x15GetPositionOptionsRes\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.position.v1.PositionOptionR\x04list2\xf3\x03\n" +
	"\bPosition\x12J\n" +
	"\fListPosition\x12\x1c.position.v1.ListPositionReq\x1a\x1c.position.v1.ListPositionRes\x12G\n" +
	"\vGetPosition\x12\x1b.position.v1.GetPositionReq\x1a\x1b.position.v1.GetPositionRes\x12P\n" +
	"\x0eCreatePosition\x12\x1e.position.v1.CreatePositionReq\x1a\x1e.position.v1.CreatePositionRes\x12P\n" +
	"\x0eUpdatePosition\x12\x1e.position.v1.UpdatePositionReq\x1a\x1e.position.v1.UpdatePositionRes\x12P\n" +
	"\x0eDeletePosition\x12\x1e.position.v1.DeletePositionReq\x1a\x1e.position.v1.DeletePositionRes\x12\\\n" +
	"\x12GetPositionOptions\x12\".position.v1.GetPositionOptionsReq\x1a\".position.v1.GetPositionOptionsResB\x13Z\x11./api/position/v1b\x06proto3"

var (
	file_position_v1_position_proto_rawDescOnce sync.Once
	file_position_v1_position_proto_rawDescData []byte
)

func file_position_v1_position_proto_rawDescGZIP() []byte {
	file_position_v1_position_proto_rawDescOnce.Do(func() {
		file_position_v1_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_v1_position_proto_rawDesc), len(file_position_v1_position_proto_rawDesc)))
	})
	return file_position_v1_position_proto_rawDescData
}

var file_position_v1_position_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_position_v1_position_proto_goTypes = []any{
	(*ListPositionReq)(nil),       // 0: position.v1.ListPositionReq
	(*PositionListItem)(nil),      // 1: position.v1.PositionListItem
	(*ListPositionRes)(nil),       // 2: position.v1.ListPositionRes
	(*GetPositionReq)(nil),        // 3: position.v1.GetPositionReq
	(*GetPositionRes)(nil),        // 4: position.v1.GetPositionRes
	(*CreatePositionReq)(nil),     // 5: position.v1.CreatePositionReq
	(*CreatePositionRes)(nil),     // 6: position.v1.CreatePositionRes
	(*UpdatePositionReq)(nil),     // 7: position.v1.UpdatePositionReq
	(*UpdatePositionRes)(nil),     // 8: position.v1.UpdatePositionRes
	(*DeletePositionReq)(nil),     // 9: position.v1.DeletePositionReq
	(*DeletePositionRes)(nil),     // 10: position.v1.DeletePositionRes
	(*GetPositionOptionsReq)(nil), // 11: position.v1.GetPositionOptionsReq
	(*PositionOption)(nil),        // 12: position.v1.PositionOption
	(*GetPositionOptionsRes)(nil), // 13: position.v1.GetPositionOptionsRes
}
var file_position_v1_position_proto_depIdxs = []int32{
	1,  // 0: position.v1.ListPositionRes.list:type_name -> position.v1.PositionListItem
	12, // 1: position.v1.GetPositionOptionsRes.list:type_name -> position.v1.PositionOption
	0,  // 2: position.v1.Position.ListPosition:input_type -> position.v1.ListPositionReq
	3,  // 3: position.v1.Position.GetPosition:input_type -> position.v1.GetPositionReq
	5,  // 4: position.v1.Position.CreatePosition:input_type -> position.v1.CreatePositionReq
	7,  // 5: position.v1.Position.UpdatePosition:input_type -> position.v1.UpdatePositionReq
	9,  // 6: position.v1.Position.DeletePosition:input_type -> position.v1.DeletePositionReq
	11, // 7: position.v1.Position.GetPositionOptions:input_type -> position.v1.GetPositionOptionsReq
	2,  // 8: position.v1.Position.ListPosition:output_type -> position.v1.ListPositionRes
	4,  // 9: position.v1.Position.GetPosition:output_type -> position.v1.GetPositionRes
	6,  // 10: position.v1.Position.CreatePosition:output_type -> position.v1.CreatePositionRes
	8,  // 11: position.v1.Position.UpdatePosition:output_type -> position.v1.UpdatePositionRes
	10, // 12: position.v1.Position.DeletePosition:output_type -> position.v1.DeletePositionRes
	13, // 13: position.v1.Position.GetPositionOptions:output_type -> position.v1.GetPositionOptionsRes
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_position_v1_position_proto_init() }
func file_position_v1_position_proto_init() {
	if File_position_v1_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_v1_position_proto_rawDesc), len(file_position_v1_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_v1_position_proto_goTypes,
		DependencyIndexes: file_position_v1_position_proto_depIdxs,
		MessageInfos:      file_position_v1_position_proto_msgTypes,
	}.Build()
	File_position_v1_position_proto = out.File
	file_position_v1_position_proto_goTypes = nil
	file_position_v1_position_proto_depIdxs = nil
}
