// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: position/v1/position.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Position_ListPosition_FullMethodName       = "/position.v1.Position/ListPosition"
	Position_GetPosition_FullMethodName        = "/position.v1.Position/GetPosition"
	Position_CreatePosition_FullMethodName     = "/position.v1.Position/CreatePosition"
	Position_UpdatePosition_FullMethodName     = "/position.v1.Position/UpdatePosition"
	Position_DeletePosition_FullMethodName     = "/position.v1.Position/DeletePosition"
	Position_GetPositionOptions_FullMethodName = "/position.v1.Position/GetPositionOptions"
)

// PositionClient is the client API for Position service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PositionClient interface {
	// 职务列表
	ListPosition(ctx context.Context, in *ListPositionReq, opts ...grpc.CallOption) (*ListPositionRes, error)
	// 获取职务详情
	GetPosition(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*GetPositionRes, error)
	// 新建职务
	CreatePosition(ctx context.Context, in *CreatePositionReq, opts ...grpc.CallOption) (*CreatePositionRes, error)
	// 编辑职务
	UpdatePosition(ctx context.Context, in *UpdatePositionReq, opts ...grpc.CallOption) (*UpdatePositionRes, error)
	// 删除职务
	DeletePosition(ctx context.Context, in *DeletePositionReq, opts ...grpc.CallOption) (*DeletePositionRes, error)
	// 按组织获取可选职务集合
	GetPositionOptions(ctx context.Context, in *GetPositionOptionsReq, opts ...grpc.CallOption) (*GetPositionOptionsRes, error)
}

type positionClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionClient(cc grpc.ClientConnInterface) PositionClient {
	return &positionClient{cc}
}

func (c *positionClient) ListPosition(ctx context.Context, in *ListPositionReq, opts ...grpc.CallOption) (*ListPositionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionRes)
	err := c.cc.Invoke(ctx, Position_ListPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) GetPosition(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*GetPositionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionRes)
	err := c.cc.Invoke(ctx, Position_GetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) CreatePosition(ctx context.Context, in *CreatePositionReq, opts ...grpc.CallOption) (*CreatePositionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePositionRes)
	err := c.cc.Invoke(ctx, Position_CreatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) UpdatePosition(ctx context.Context, in *UpdatePositionReq, opts ...grpc.CallOption) (*UpdatePositionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePositionRes)
	err := c.cc.Invoke(ctx, Position_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) DeletePosition(ctx context.Context, in *DeletePositionReq, opts ...grpc.CallOption) (*DeletePositionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePositionRes)
	err := c.cc.Invoke(ctx, Position_DeletePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionClient) GetPositionOptions(ctx context.Context, in *GetPositionOptionsReq, opts ...grpc.CallOption) (*GetPositionOptionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPositionOptionsRes)
	err := c.cc.Invoke(ctx, Position_GetPositionOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionServer is the server API for Position service.
// All implementations must embed UnimplementedPositionServer
// for forward compatibility.
type PositionServer interface {
	// 职务列表
	ListPosition(context.Context, *ListPositionReq) (*ListPositionRes, error)
	// 获取职务详情
	GetPosition(context.Context, *GetPositionReq) (*GetPositionRes, error)
	// 新建职务
	CreatePosition(context.Context, *CreatePositionReq) (*CreatePositionRes, error)
	// 编辑职务
	UpdatePosition(context.Context, *UpdatePositionReq) (*UpdatePositionRes, error)
	// 删除职务
	DeletePosition(context.Context, *DeletePositionReq) (*DeletePositionRes, error)
	// 按组织获取可选职务集合
	GetPositionOptions(context.Context, *GetPositionOptionsReq) (*GetPositionOptionsRes, error)
	mustEmbedUnimplementedPositionServer()
}

// UnimplementedPositionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPositionServer struct{}

func (UnimplementedPositionServer) ListPosition(context.Context, *ListPositionReq) (*ListPositionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPosition not implemented")
}
func (UnimplementedPositionServer) GetPosition(context.Context, *GetPositionReq) (*GetPositionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedPositionServer) CreatePosition(context.Context, *CreatePositionReq) (*CreatePositionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePosition not implemented")
}
func (UnimplementedPositionServer) UpdatePosition(context.Context, *UpdatePositionReq) (*UpdatePositionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedPositionServer) DeletePosition(context.Context, *DeletePositionReq) (*DeletePositionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePosition not implemented")
}
func (UnimplementedPositionServer) GetPositionOptions(context.Context, *GetPositionOptionsReq) (*GetPositionOptionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionOptions not implemented")
}
func (UnimplementedPositionServer) mustEmbedUnimplementedPositionServer() {}
func (UnimplementedPositionServer) testEmbeddedByValue()                  {}

// UnsafePositionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionServer will
// result in compilation errors.
type UnsafePositionServer interface {
	mustEmbedUnimplementedPositionServer()
}

func RegisterPositionServer(s grpc.ServiceRegistrar, srv PositionServer) {
	// If the following call panics, it indicates UnimplementedPositionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Position_ServiceDesc, srv)
}

func _Position_ListPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).ListPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_ListPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).ListPosition(ctx, req.(*ListPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).GetPosition(ctx, req.(*GetPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_CreatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).CreatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_CreatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).CreatePosition(ctx, req.(*CreatePositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).UpdatePosition(ctx, req.(*UpdatePositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_DeletePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).DeletePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_DeletePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).DeletePosition(ctx, req.(*DeletePositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Position_GetPositionOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionOptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServer).GetPositionOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Position_GetPositionOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServer).GetPositionOptions(ctx, req.(*GetPositionOptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Position_ServiceDesc is the grpc.ServiceDesc for Position service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Position_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "position.v1.Position",
	HandlerType: (*PositionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPosition",
			Handler:    _Position_ListPosition_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _Position_GetPosition_Handler,
		},
		{
			MethodName: "CreatePosition",
			Handler:    _Position_CreatePosition_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _Position_UpdatePosition_Handler,
		},
		{
			MethodName: "DeletePosition",
			Handler:    _Position_DeletePosition_Handler,
		},
		{
			MethodName: "GetPositionOptions",
			Handler:    _Position_GetPositionOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "position/v1/position.proto",
}
