// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: pbentity/member.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Member struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                                             // 主键
	Username         string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty" dc:"账号(<=20), 不可重复"`                      // 账号(<=20), 不可重复
	Name             string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" dc:"姓名(<=10)"`                                    // 姓名(<=10)
	Gender           uint32                 `protobuf:"varint,4,opt,name=Gender,proto3" json:"Gender,omitempty" dc:"性别:1男2女(可扩展0未知)"`                        // 性别:1男2女(可扩展0未知)
	Mobile           string                 `protobuf:"bytes,5,opt,name=Mobile,proto3" json:"Mobile,omitempty" dc:"手机号(11位数字)"`                              // 手机号(11位数字)
	Status           uint32                 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态:1启用0禁用"`                              // 状态:1启用0禁用
	IsSuperAdmin     uint32                 `protobuf:"varint,7,opt,name=IsSuperAdmin,proto3" json:"IsSuperAdmin,omitempty" dc:"超级管理员:1是0否"`                 // 超级管理员:1是0否
	PasswordHash     string                 `protobuf:"bytes,8,opt,name=PasswordHash,proto3" json:"PasswordHash,omitempty" dc:"密码hash"`                      // 密码hash
	LastLoginAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=LastLoginAt,proto3" json:"LastLoginAt,omitempty" dc:"最近一次登录时间"`                      // 最近一次登录时间
	ResignedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ResignedAt,proto3" json:"ResignedAt,omitempty" dc:"离职时间(非空表示离职)"`                   // 离职时间(非空表示离职)
	SuperAdminUnique int32                  `protobuf:"varint,11,opt,name=SuperAdminUnique,proto3" json:"SuperAdminUnique,omitempty" dc:"仅用于保证超管唯一(业务字段勿用)"` // 仅用于保证超管唯一(业务字段勿用)
	IsDeleted        uint32                 `protobuf:"varint,12,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"数据状态0正常1删除"`                      // 数据状态0正常1删除
	CreateBy         uint64                 `protobuf:"varint,13,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`                               // 创建人
	UpdateBy         uint64                 `protobuf:"varint,14,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`                               // 修改人
	DeleteBy         uint64                 `protobuf:"varint,15,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`                               // 删除人
	CreateAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`                               // 创建时间
	UpdateAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`                               // 更新时间
	DeletedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`                             // 删除时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_pbentity_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_pbentity_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Member) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Member) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Member) GetIsSuperAdmin() uint32 {
	if x != nil {
		return x.IsSuperAdmin
	}
	return 0
}

func (x *Member) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *Member) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

func (x *Member) GetResignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResignedAt
	}
	return nil
}

func (x *Member) GetSuperAdminUnique() int32 {
	if x != nil {
		return x.SuperAdminUnique
	}
	return 0
}

func (x *Member) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *Member) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Member) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *Member) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *Member) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *Member) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *Member) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_member_proto protoreflect.FileDescriptor

const file_pbentity_member_proto_rawDesc = "" +
	"\n" +
	"\x15pbentity/member.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x05\n" +
	"\x06Member\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Gender\x18\x04 \x01(\rR\x06Gender\x12\x16\n" +
	"\x06Mobile\x18\x05 \x01(\tR\x06Mobile\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\rR\x06Status\x12\"\n" +
	"\fIsSuperAdmin\x18\a \x01(\rR\fIsSuperAdmin\x12\"\n" +
	"\fPasswordHash\x18\b \x01(\tR\fPasswordHash\x12<\n" +
	"\vLastLoginAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vLastLoginAt\x12:\n" +
	"\n" +
	"ResignedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ResignedAt\x12*\n" +
	"\x10SuperAdminUnique\x18\v \x01(\x05R\x10SuperAdminUnique\x12\x1c\n" +
	"\tIsDeleted\x18\f \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\r \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\x0e \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\x0f \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dfreeroam/app/org/api/pbentityb\x06proto3"

var (
	file_pbentity_member_proto_rawDescOnce sync.Once
	file_pbentity_member_proto_rawDescData []byte
)

func file_pbentity_member_proto_rawDescGZIP() []byte {
	file_pbentity_member_proto_rawDescOnce.Do(func() {
		file_pbentity_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_member_proto_rawDesc), len(file_pbentity_member_proto_rawDesc)))
	})
	return file_pbentity_member_proto_rawDescData
}

var file_pbentity_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_member_proto_goTypes = []any{
	(*Member)(nil),                // 0: pbentity.Member
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_member_proto_depIdxs = []int32{
	1, // 0: pbentity.Member.LastLoginAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.Member.ResignedAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.Member.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 3: pbentity.Member.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 4: pbentity.Member.DeletedAt:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pbentity_member_proto_init() }
func file_pbentity_member_proto_init() {
	if File_pbentity_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_member_proto_rawDesc), len(file_pbentity_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_member_proto_goTypes,
		DependencyIndexes: file_pbentity_member_proto_depIdxs,
		MessageInfos:      file_pbentity_member_proto_msgTypes,
	}.Build()
	File_pbentity_member_proto = out.File
	file_pbentity_member_proto_goTypes = nil
	file_pbentity_member_proto_depIdxs = nil
}
