// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pbentity/org.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Org struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                         // 主键
	ParentId      uint64                 `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty" dc:"父组织ID, 0为顶级"`    // 父组织ID, 0为顶级
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" dc:"组织名称"`                    // 组织名称
	FullName      string                 `protobuf:"bytes,4,opt,name=FullName,proto3" json:"FullName,omitempty" dc:"组织全称"`            // 组织全称
	Code          string                 `protobuf:"bytes,5,opt,name=Code,proto3" json:"Code,omitempty" dc:"组织编码"`                    // 组织编码
	Category      string                 `protobuf:"bytes,6,opt,name=Category,proto3" json:"Category,omitempty" dc:"分类:org_category"` // 分类:org_category
	Status        string                 `protobuf:"bytes,7,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态:org_status"`       // 状态:org_status
	Sort          int32                  `protobuf:"varint,8,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"同级排序"`                   // 同级排序
	Path          string                 `protobuf:"bytes,9,opt,name=Path,proto3" json:"Path,omitempty" dc:"物化路径, 如 /1/10/"`          // 物化路径, 如 /1/10/
	IsDeleted     uint32                 `protobuf:"varint,10,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"是否删除0:否,1:是"` // 是否删除0:否,1:是
	CreateBy      uint64                 `protobuf:"varint,11,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`           // 创建人
	UpdateBy      uint64                 `protobuf:"varint,12,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`           // 修改人
	DeleteBy      uint64                 `protobuf:"varint,13,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`           // 删除人
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`           // 创建时间
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`           // 更新时间
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`         // 删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Org) Reset() {
	*x = Org{}
	mi := &file_pbentity_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Org) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Org) ProtoMessage() {}

func (x *Org) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Org.ProtoReflect.Descriptor instead.
func (*Org) Descriptor() ([]byte, []int) {
	return file_pbentity_org_proto_rawDescGZIP(), []int{0}
}

func (x *Org) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Org) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Org) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Org) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Org) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Org) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Org) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Org) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Org) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Org) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *Org) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Org) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *Org) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *Org) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *Org) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *Org) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_org_proto protoreflect.FileDescriptor

const file_pbentity_org_proto_rawDesc = "" +
	"\n" +
	"\x12pbentity/org.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n" +
	"\x03Org\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x1a\n" +
	"\bParentId\x18\x02 \x01(\x04R\bParentId\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFullName\x18\x04 \x01(\tR\bFullName\x12\x12\n" +
	"\x04Code\x18\x05 \x01(\tR\x04Code\x12\x1a\n" +
	"\bCategory\x18\x06 \x01(\tR\bCategory\x12\x16\n" +
	"\x06Status\x18\a \x01(\tR\x06Status\x12\x12\n" +
	"\x04Sort\x18\b \x01(\x05R\x04Sort\x12\x12\n" +
	"\x04Path\x18\t \x01(\tR\x04Path\x12\x1c\n" +
	"\tIsDeleted\x18\n" +
	" \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\v \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\f \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\r \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dfreeroam/app/org/api/pbentityb\x06proto3"

var (
	file_pbentity_org_proto_rawDescOnce sync.Once
	file_pbentity_org_proto_rawDescData []byte
)

func file_pbentity_org_proto_rawDescGZIP() []byte {
	file_pbentity_org_proto_rawDescOnce.Do(func() {
		file_pbentity_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_org_proto_rawDesc), len(file_pbentity_org_proto_rawDesc)))
	})
	return file_pbentity_org_proto_rawDescData
}

var file_pbentity_org_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_org_proto_goTypes = []any{
	(*Org)(nil),                   // 0: pbentity.Org
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_org_proto_depIdxs = []int32{
	1, // 0: pbentity.Org.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.Org.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.Org.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_org_proto_init() }
func file_pbentity_org_proto_init() {
	if File_pbentity_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_org_proto_rawDesc), len(file_pbentity_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_org_proto_goTypes,
		DependencyIndexes: file_pbentity_org_proto_depIdxs,
		MessageInfos:      file_pbentity_org_proto_msgTypes,
	}.Build()
	File_pbentity_org_proto = out.File
	file_pbentity_org_proto_goTypes = nil
	file_pbentity_org_proto_depIdxs = nil
}
