// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pbentity/position_org.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionOrg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                        // 主键
	PositionId    uint64                 `protobuf:"varint,2,opt,name=PositionId,proto3" json:"PositionId,omitempty" dc:"职务ID"`      // 职务ID
	OrgId         uint64                 `protobuf:"varint,3,opt,name=OrgId,proto3" json:"OrgId,omitempty" dc:"组织ID"`                // 组织ID
	IsDeleted     uint32                 `protobuf:"varint,4,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"是否删除0:否,1:是"` // 是否删除0:否,1:是
	CreateBy      uint64                 `protobuf:"varint,5,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`           // 创建人
	UpdateBy      uint64                 `protobuf:"varint,6,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`           // 修改人
	DeleteBy      uint64                 `protobuf:"varint,7,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`           // 删除人
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`           // 创建时间
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`           // 更新时间
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`        // 删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionOrg) Reset() {
	*x = PositionOrg{}
	mi := &file_pbentity_position_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionOrg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionOrg) ProtoMessage() {}

func (x *PositionOrg) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_position_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionOrg.ProtoReflect.Descriptor instead.
func (*PositionOrg) Descriptor() ([]byte, []int) {
	return file_pbentity_position_org_proto_rawDescGZIP(), []int{0}
}

func (x *PositionOrg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionOrg) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *PositionOrg) GetOrgId() uint64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *PositionOrg) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *PositionOrg) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *PositionOrg) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *PositionOrg) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *PositionOrg) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *PositionOrg) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *PositionOrg) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_position_org_proto protoreflect.FileDescriptor

const file_pbentity_position_org_proto_rawDesc = "" +
	"\n" +
	"\x1bpbentity/position_org.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\vPositionOrg\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x1e\n" +
	"\n" +
	"PositionId\x18\x02 \x01(\x04R\n" +
	"PositionId\x12\x14\n" +
	"\x05OrgId\x18\x03 \x01(\x04R\x05OrgId\x12\x1c\n" +
	"\tIsDeleted\x18\x04 \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\x05 \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\x06 \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\a \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dfreeroam/app/org/api/pbentityb\x06proto3"

var (
	file_pbentity_position_org_proto_rawDescOnce sync.Once
	file_pbentity_position_org_proto_rawDescData []byte
)

func file_pbentity_position_org_proto_rawDescGZIP() []byte {
	file_pbentity_position_org_proto_rawDescOnce.Do(func() {
		file_pbentity_position_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_position_org_proto_rawDesc), len(file_pbentity_position_org_proto_rawDesc)))
	})
	return file_pbentity_position_org_proto_rawDescData
}

var file_pbentity_position_org_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_position_org_proto_goTypes = []any{
	(*PositionOrg)(nil),           // 0: pbentity.PositionOrg
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_position_org_proto_depIdxs = []int32{
	1, // 0: pbentity.PositionOrg.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.PositionOrg.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.PositionOrg.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_position_org_proto_init() }
func file_pbentity_position_org_proto_init() {
	if File_pbentity_position_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_position_org_proto_rawDesc), len(file_pbentity_position_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_position_org_proto_goTypes,
		DependencyIndexes: file_pbentity_position_org_proto_depIdxs,
		MessageInfos:      file_pbentity_position_org_proto_msgTypes,
	}.Build()
	File_pbentity_position_org_proto = out.File
	file_pbentity_position_org_proto_goTypes = nil
	file_pbentity_position_org_proto_depIdxs = nil
}
