// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pbentity/position.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                                    // 主键
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"职务名称"`                               // 职务名称
	Status        string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态:position_status"`             // 状态:position_status
	DataScope     string                 `protobuf:"bytes,4,opt,name=DataScope,proto3" json:"DataScope,omitempty" dc:"数据权限:position_data_scope"` // 数据权限:position_data_scope
	IsDeleted     uint32                 `protobuf:"varint,5,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"是否删除0:否,1:是"`             // 是否删除0:否,1:是
	CreateBy      uint64                 `protobuf:"varint,6,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`                       // 创建人
	UpdateBy      uint64                 `protobuf:"varint,7,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`                       // 修改人
	DeleteBy      uint64                 `protobuf:"varint,8,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`                       // 删除人
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`                       // 创建时间
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`                      // 更新时间
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`                    // 删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_pbentity_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pbentity_position_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Position) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *Position) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *Position) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Position) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *Position) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *Position) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *Position) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *Position) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_position_proto protoreflect.FileDescriptor

const file_pbentity_position_proto_rawDesc = "" +
	"\n" +
	"\x17pbentity/position.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\bPosition\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\x12\x1c\n" +
	"\tDataScope\x18\x04 \x01(\tR\tDataScope\x12\x1c\n" +
	"\tIsDeleted\x18\x05 \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\x06 \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\a \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\b \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dfreeroam/app/org/api/pbentityb\x06proto3"

var (
	file_pbentity_position_proto_rawDescOnce sync.Once
	file_pbentity_position_proto_rawDescData []byte
)

func file_pbentity_position_proto_rawDescGZIP() []byte {
	file_pbentity_position_proto_rawDescOnce.Do(func() {
		file_pbentity_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_position_proto_rawDesc), len(file_pbentity_position_proto_rawDesc)))
	})
	return file_pbentity_position_proto_rawDescData
}

var file_pbentity_position_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_position_proto_goTypes = []any{
	(*Position)(nil),              // 0: pbentity.Position
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_position_proto_depIdxs = []int32{
	1, // 0: pbentity.Position.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.Position.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.Position.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_position_proto_init() }
func file_pbentity_position_proto_init() {
	if File_pbentity_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_position_proto_rawDesc), len(file_pbentity_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_position_proto_goTypes,
		DependencyIndexes: file_pbentity_position_proto_depIdxs,
		MessageInfos:      file_pbentity_position_proto_msgTypes,
	}.Build()
	File_pbentity_position_proto = out.File
	file_pbentity_position_proto_goTypes = nil
	file_pbentity_position_proto_depIdxs = nil
}
