// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pbentity/user_member.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMember struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                                  // 主键
	UserId            uint64                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户ID"`                        // 用户ID
	TenantId          uint64                 `protobuf:"varint,3,opt,name=TenantId,proto3" json:"TenantId,omitempty" dc:"租户id"`                    // 租户id
	Username          string                 `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty" dc:"用户名"`                      // 用户名
	Name              string                 `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty" dc:"姓名"`                               // 姓名
	Mobile            string                 `protobuf:"bytes,6,opt,name=Mobile,proto3" json:"Mobile,omitempty" dc:"手机号"`                          // 手机号
	Gender            uint32                 `protobuf:"varint,7,opt,name=Gender,proto3" json:"Gender,omitempty" dc:"性别"`                          // 性别
	ResetPasswordTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ResetPasswordTime,proto3" json:"ResetPasswordTime,omitempty" dc:"重置密码时间"` // 重置密码时间
	Status            uint32                 `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态：0未启用，1已启用，2禁止登陆"`          // 状态：0未启用，1已启用，2禁止登陆
	Super             uint32                 `protobuf:"varint,10,opt,name=Super,proto3" json:"Super,omitempty" dc:"超级管理员，0否1是"`                   // 超级管理员，0否1是
	IsDeleted         uint32                 `protobuf:"varint,11,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"数据状态0正常1删除"`           // 数据状态0正常1删除
	CreateBy          uint64                 `protobuf:"varint,12,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`                    // 创建人
	UpdateBy          uint64                 `protobuf:"varint,13,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`                    // 修改人
	DeleteBy          uint64                 `protobuf:"varint,14,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`                    // 删除人
	CreateAt          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`                    // 创建时间
	UpdateAt          *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`                    // 更新时间
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`                  // 删除时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserMember) Reset() {
	*x = UserMember{}
	mi := &file_pbentity_user_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMember) ProtoMessage() {}

func (x *UserMember) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMember.ProtoReflect.Descriptor instead.
func (*UserMember) Descriptor() ([]byte, []int) {
	return file_pbentity_user_member_proto_rawDescGZIP(), []int{0}
}

func (x *UserMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserMember) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UserMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMember) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserMember) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserMember) GetResetPasswordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetPasswordTime
	}
	return nil
}

func (x *UserMember) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserMember) GetSuper() uint32 {
	if x != nil {
		return x.Super
	}
	return 0
}

func (x *UserMember) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *UserMember) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *UserMember) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *UserMember) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *UserMember) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *UserMember) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *UserMember) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_user_member_proto protoreflect.FileDescriptor

const file_pbentity_user_member_proto_rawDesc = "" +
	"\n" +
	"\x1apbentity/user_member.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x04\n" +
	"\n" +
	"UserMember\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x04R\x06UserId\x12\x1a\n" +
	"\bTenantId\x18\x03 \x01(\x04R\bTenantId\x12\x1a\n" +
	"\bUsername\x18\x04 \x01(\tR\bUsername\x12\x12\n" +
	"\x04Name\x18\x05 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Mobile\x18\x06 \x01(\tR\x06Mobile\x12\x16\n" +
	"\x06Gender\x18\a \x01(\rR\x06Gender\x12H\n" +
	"\x11ResetPasswordTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11ResetPasswordTime\x12\x16\n" +
	"\x06Status\x18\t \x01(\rR\x06Status\x12\x14\n" +
	"\x05Super\x18\n" +
	" \x01(\rR\x05Super\x12\x1c\n" +
	"\tIsDeleted\x18\v \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\f \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\r \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\x0e \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1fZ\x1dfreeroam/app/org/api/pbentityb\x06proto3"

var (
	file_pbentity_user_member_proto_rawDescOnce sync.Once
	file_pbentity_user_member_proto_rawDescData []byte
)

func file_pbentity_user_member_proto_rawDescGZIP() []byte {
	file_pbentity_user_member_proto_rawDescOnce.Do(func() {
		file_pbentity_user_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_user_member_proto_rawDesc), len(file_pbentity_user_member_proto_rawDesc)))
	})
	return file_pbentity_user_member_proto_rawDescData
}

var file_pbentity_user_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_user_member_proto_goTypes = []any{
	(*UserMember)(nil),            // 0: pbentity.UserMember
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_user_member_proto_depIdxs = []int32{
	1, // 0: pbentity.UserMember.ResetPasswordTime:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.UserMember.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.UserMember.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 3: pbentity.UserMember.DeletedAt:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pbentity_user_member_proto_init() }
func file_pbentity_user_member_proto_init() {
	if File_pbentity_user_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_user_member_proto_rawDesc), len(file_pbentity_user_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_user_member_proto_goTypes,
		DependencyIndexes: file_pbentity_user_member_proto_depIdxs,
		MessageInfos:      file_pbentity_user_member_proto_msgTypes,
	}.Build()
	File_pbentity_user_member_proto = out.File
	file_pbentity_user_member_proto_goTypes = nil
	file_pbentity_user_member_proto_depIdxs = nil
}
