// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// memberOrgPositionDao is the data access object for the table free_member_org_position.
// You can define custom methods on it to extend its functionality as needed.
type memberOrgPositionDao struct {
	*internal.MemberOrgPositionDao
}

var (
	// MemberOrgPosition is a globally accessible object for table free_member_org_position operations.
	MemberOrgPosition = memberOrgPositionDao{internal.NewMemberOrgPositionDao()}
)

// Add your custom methods and functionality below.
