// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// memberDao is the data access object for the table free_member.
// You can define custom methods on it to extend its functionality as needed.
type memberDao struct {
	*internal.MemberDao
}

var (
	// Member is a globally accessible object for table free_member operations.
	Member = memberDao{internal.NewMemberDao()}
)

// Add your custom methods and functionality below.
