// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// orgStructureDao is the data access object for the table free_org_structure.
// You can define custom methods on it to extend its functionality as needed.
type orgStructureDao struct {
	*internal.OrgStructureDao
}

var (
	// OrgStructure is a globally accessible object for table free_org_structure operations.
	OrgStructure = orgStructureDao{internal.NewOrgStructureDao()}
)

// Add your custom methods and functionality below.
