// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// orgSupervisorDao is the data access object for the table free_org_supervisor.
// You can define custom methods on it to extend its functionality as needed.
type orgSupervisorDao struct {
	*internal.OrgSupervisorDao
}

var (
	// OrgSupervisor is a globally accessible object for table free_org_supervisor operations.
	OrgSupervisor = orgSupervisorDao{internal.NewOrgSupervisorDao()}
)

// Add your custom methods and functionality below.
