// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// positionDao is the data access object for the table free_position.
// You can define custom methods on it to extend its functionality as needed.
type positionDao struct {
	*internal.PositionDao
}

var (
	// Position is a globally accessible object for table free_position operations.
	Position = positionDao{internal.NewPositionDao()}
)

// Add your custom methods and functionality below.
