// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// positionRoleDao is the data access object for the table free_position_role.
// You can define custom methods on it to extend its functionality as needed.
type positionRoleDao struct {
	*internal.PositionRoleDao
}

var (
	// PositionRole is a globally accessible object for table free_position_role operations.
	PositionRole = positionRoleDao{internal.NewPositionRoleDao()}
)

// Add your custom methods and functionality below.
