// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// positionOrgDao is the data access object for the table free_position_org.
// You can define custom methods on it to extend its functionality as needed.
type positionOrgDao struct {
	*internal.PositionOrgDao
}

var (
	// PositionOrg is a globally accessible object for table free_position_org operations.
	PositionOrg = positionOrgDao{internal.NewPositionOrgDao()}
)

// Add your custom methods and functionality below.
