// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"freeroam/app/org/internal/dao/internal"
)

// roleDao is the data access object for the table free_role.
// You can define custom methods on it to extend its functionality as needed.
type roleDao struct {
	*internal.RoleDao
}

var (
	// Role is a globally accessible object for table free_role operations.
	Role = roleDao{internal.NewRoleDao()}
)

// Add your custom methods and functionality below.

func (r *roleDao) CheckCodeExists(ctx context.Context, code string) (bool, error) {
	return r.Ctx(ctx).
		Where(r.Columns().Code, code).
		Where(r.Columns().IsDeleted, false).
		Exist()
}

func (r *roleDao) CheckRoleExists(ctx context.Context, roleId int64) (bool, error) {
	return r.Ctx(ctx).
		Where(r.Columns().Id, roleId).
		Where(r.Columns().IsDeleted, false).
		Exist()
}
