// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"freeroam/app/org/internal/dao/internal"
)

// userMemberRoleDao is the data access object for the table free_user_member_role.
// You can define custom methods on it to extend its functionality as needed.
type userMemberRoleDao struct {
	*internal.UserMemberRoleDao
}

var (
	// UserMemberRole is a globally accessible object for table free_user_member_role operations.
	UserMemberRole = userMemberRoleDao{internal.NewUserMemberRoleDao()}
)

// Add your custom methods and functionality below.
