// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bbk/app/org/internal/dao/internal"
)

// userMemberDao is the data access object for the table free_user_member.
// You can define custom methods on it to extend its functionality as needed.
type userMemberDao struct {
	*internal.UserMemberDao
}

var (
	// UserMember is a globally accessible object for table free_user_member operations.
	UserMember = userMemberDao{internal.NewUserMemberDao()}
)

// Add your custom methods and functionality below.
