// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: auth/v1/auth.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateMemberCredentialReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账号
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" dc:"账号" v:"required#账号不能为空"` // v:required#账号不能为空
	// 密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" dc:"密码" v:"required#密码不能为空"` // v:required#密码不能为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMemberCredentialReq) Reset() {
	*x = ValidateMemberCredentialReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberCredentialReq) ProtoMessage() {}

func (x *ValidateMemberCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberCredentialReq.ProtoReflect.Descriptor instead.
func (*ValidateMemberCredentialReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateMemberCredentialReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateMemberCredentialReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidateMemberCredentialRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员ID
	MemberId uint64 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty" dc:"成员ID"`
	// 账号
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" dc:"账号"`
	// 姓名
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 状态:1启用0禁用
	Status uint32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" dc:"状态:1启用0禁用"`
	// 是否已离职(非空表示离职)
	ResignedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=resigned_at,json=resignedAt,proto3" json:"resigned_at,omitempty" dc:"是否已离职(非空表示离职)"`
	// 是否已删除
	IsDeleted     uint32 `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty" dc:"是否已删除"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateMemberCredentialRes) Reset() {
	*x = ValidateMemberCredentialRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateMemberCredentialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateMemberCredentialRes) ProtoMessage() {}

func (x *ValidateMemberCredentialRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateMemberCredentialRes.ProtoReflect.Descriptor instead.
func (*ValidateMemberCredentialRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateMemberCredentialRes) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ValidateMemberCredentialRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateMemberCredentialRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateMemberCredentialRes) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ValidateMemberCredentialRes) GetResignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResignedAt
	}
	return nil
}

func (x *ValidateMemberCredentialRes) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n" +
	"\x1bValidateMemberCredentialReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xde\x01\n" +
	"\x1bValidateMemberCredentialRes\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12;\n" +
	"\vresigned_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resignedAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\rR\tisDeleted2n\n" +
	"\x04Auth\x12f\n" +
	"\x18ValidateMemberCredential\x12$.auth.v1.ValidateMemberCredentialReq\x1a$.auth.v1.ValidateMemberCredentialResB\x0fZ\r./api/auth/v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_v1_auth_proto_goTypes = []any{
	(*ValidateMemberCredentialReq)(nil), // 0: auth.v1.ValidateMemberCredentialReq
	(*ValidateMemberCredentialRes)(nil), // 1: auth.v1.ValidateMemberCredentialRes
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: auth.v1.ValidateMemberCredentialRes.resigned_at:type_name -> google.protobuf.Timestamp
	0, // 1: auth.v1.Auth.ValidateMemberCredential:input_type -> auth.v1.ValidateMemberCredentialReq
	1, // 2: auth.v1.Auth.ValidateMemberCredential:output_type -> auth.v1.ValidateMemberCredentialRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
