// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: permission/v1/permission.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Permission_AssignRolePermissions_FullMethodName = "/permission.v1.Permission/AssignRolePermissions"
	Permission_GetRolePermissions_FullMethodName    = "/permission.v1.Permission/GetRolePermissions"
	Permission_GetPermissionTree_FullMethodName     = "/permission.v1.Permission/GetPermissionTree"
	Permission_GetMemberPermissions_FullMethodName  = "/permission.v1.Permission/GetMemberPermissions"
)

// PermissionClient is the client API for Permission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionClient interface {
	// 角色权限分配
	AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsReq, opts ...grpc.CallOption) (*AssignRolePermissionsRes, error)
	// 查询角色权限
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsRes, error)
	// 查询权限资源树
	GetPermissionTree(ctx context.Context, in *GetPermissionTreeReq, opts ...grpc.CallOption) (*GetPermissionTreeRes, error)
	// 获取用户权限
	GetMemberPermissions(ctx context.Context, in *GetMemberPermissionsReq, opts ...grpc.CallOption) (*GetMemberPermissionsRes, error)
}

type permissionClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionClient(cc grpc.ClientConnInterface) PermissionClient {
	return &permissionClient{cc}
}

func (c *permissionClient) AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsReq, opts ...grpc.CallOption) (*AssignRolePermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRolePermissionsRes)
	err := c.cc.Invoke(ctx, Permission_AssignRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsRes)
	err := c.cc.Invoke(ctx, Permission_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetPermissionTree(ctx context.Context, in *GetPermissionTreeReq, opts ...grpc.CallOption) (*GetPermissionTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionTreeRes)
	err := c.cc.Invoke(ctx, Permission_GetPermissionTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionClient) GetMemberPermissions(ctx context.Context, in *GetMemberPermissionsReq, opts ...grpc.CallOption) (*GetMemberPermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberPermissionsRes)
	err := c.cc.Invoke(ctx, Permission_GetMemberPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServer is the server API for Permission service.
// All implementations must embed UnimplementedPermissionServer
// for forward compatibility.
type PermissionServer interface {
	// 角色权限分配
	AssignRolePermissions(context.Context, *AssignRolePermissionsReq) (*AssignRolePermissionsRes, error)
	// 查询角色权限
	GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsRes, error)
	// 查询权限资源树
	GetPermissionTree(context.Context, *GetPermissionTreeReq) (*GetPermissionTreeRes, error)
	// 获取用户权限
	GetMemberPermissions(context.Context, *GetMemberPermissionsReq) (*GetMemberPermissionsRes, error)
	mustEmbedUnimplementedPermissionServer()
}

// UnimplementedPermissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServer struct{}

func (UnimplementedPermissionServer) AssignRolePermissions(context.Context, *AssignRolePermissionsReq) (*AssignRolePermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRolePermissions not implemented")
}
func (UnimplementedPermissionServer) GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedPermissionServer) GetPermissionTree(context.Context, *GetPermissionTreeReq) (*GetPermissionTreeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionTree not implemented")
}
func (UnimplementedPermissionServer) GetMemberPermissions(context.Context, *GetMemberPermissionsReq) (*GetMemberPermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberPermissions not implemented")
}
func (UnimplementedPermissionServer) mustEmbedUnimplementedPermissionServer() {}
func (UnimplementedPermissionServer) testEmbeddedByValue()                    {}

// UnsafePermissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServer will
// result in compilation errors.
type UnsafePermissionServer interface {
	mustEmbedUnimplementedPermissionServer()
}

func RegisterPermissionServer(s grpc.ServiceRegistrar, srv PermissionServer) {
	// If the following call panics, it indicates UnimplementedPermissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Permission_ServiceDesc, srv)
}

func _Permission_AssignRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).AssignRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_AssignRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).AssignRolePermissions(ctx, req.(*AssignRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetRolePermissions(ctx, req.(*GetRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetPermissionTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetPermissionTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_GetPermissionTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetPermissionTree(ctx, req.(*GetPermissionTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permission_GetMemberPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServer).GetMemberPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permission_GetMemberPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServer).GetMemberPermissions(ctx, req.(*GetMemberPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Permission_ServiceDesc is the grpc.ServiceDesc for Permission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.v1.Permission",
	HandlerType: (*PermissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRolePermissions",
			Handler:    _Permission_AssignRolePermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _Permission_GetRolePermissions_Handler,
		},
		{
			MethodName: "GetPermissionTree",
			Handler:    _Permission_GetPermissionTree_Handler,
		},
		{
			MethodName: "GetMemberPermissions",
			Handler:    _Permission_GetMemberPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permission/v1/permission.proto",
}
