// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: permission/v1/permission.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色权限分配请求
type AssignRolePermissionsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	RoleId int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	// 权限标识列表
	PermCodes     []string `protobuf:"bytes,2,rep,name=permCodes,proto3" json:"permCodes,omitempty" dc:"权限标识列表" v:"required|min-length:1#权限标识列表不能为空|至少需要一个权限标识"` // v:required|min-length:1#权限标识列表不能为空|至少需要一个权限标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionsReq) Reset() {
	*x = AssignRolePermissionsReq{}
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionsReq) ProtoMessage() {}

func (x *AssignRolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionsReq.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRolePermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignRolePermissionsReq) GetPermCodes() []string {
	if x != nil {
		return x.PermCodes
	}
	return nil
}

// 角色权限分配响应
type AssignRolePermissionsRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty" dc:"是否成功"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolePermissionsRes) Reset() {
	*x = AssignRolePermissionsRes{}
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolePermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolePermissionsRes) ProtoMessage() {}

func (x *AssignRolePermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolePermissionsRes.ProtoReflect.Descriptor instead.
func (*AssignRolePermissionsRes) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *AssignRolePermissionsRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 查询角色权限请求
type GetRolePermissionsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色ID
	RoleId        int64 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty" dc:"角色ID" v:"required|min:1#角色ID不能为空|角色ID必须大于0"` // v:required|min:1#角色ID不能为空|角色ID必须大于0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsReq) Reset() {
	*x = GetRolePermissionsReq{}
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsReq) ProtoMessage() {}

func (x *GetRolePermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsReq.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsReq) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *GetRolePermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 查询角色权限响应
type GetRolePermissionsRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID列表
	PermissionIds []int64 `protobuf:"varint,1,rep,packed,name=permissionIds,proto3" json:"permissionIds,omitempty" dc:"权限ID列表"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRes) Reset() {
	*x = GetRolePermissionsRes{}
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRes) ProtoMessage() {}

func (x *GetRolePermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRes.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRes) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *GetRolePermissionsRes) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// 查询权限资源树请求
type GetPermissionTreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionTreeReq) Reset() {
	*x = GetPermissionTreeReq{}
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionTreeReq) ProtoMessage() {}

func (x *GetPermissionTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionTreeReq.ProtoReflect.Descriptor instead.
func (*GetPermissionTreeReq) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{4}
}

// 查询权限资源树响应
type GetPermissionTreeRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限树
	Tree          []*PermissionTreeNode `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty" dc:"权限树"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionTreeRes) Reset() {
	*x = GetPermissionTreeRes{}
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionTreeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionTreeRes) ProtoMessage() {}

func (x *GetPermissionTreeRes) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionTreeRes.ProtoReflect.Descriptor instead.
func (*GetPermissionTreeRes) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *GetPermissionTreeRes) GetTree() []*PermissionTreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

// 权限树节点
type PermissionTreeNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"权限ID"`
	// 权限标识
	PermCode string `protobuf:"bytes,2,opt,name=permCode,proto3" json:"permCode,omitempty" dc:"权限标识"`
	// 权限名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"权限名称"`
	// 权限类型:permissions_type
	PermType string `protobuf:"bytes,4,opt,name=permType,proto3" json:"permType,omitempty" dc:"权限类型:permissions_type"`
	// 子节点
	Children      []*PermissionTreeNode `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty" dc:"子节点"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeNode) Reset() {
	*x = PermissionTreeNode{}
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeNode) ProtoMessage() {}

func (x *PermissionTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeNode.ProtoReflect.Descriptor instead.
func (*PermissionTreeNode) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{6}
}

func (x *PermissionTreeNode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionTreeNode) GetPermCode() string {
	if x != nil {
		return x.PermCode
	}
	return ""
}

func (x *PermissionTreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionTreeNode) GetPermType() string {
	if x != nil {
		return x.PermType
	}
	return ""
}

func (x *PermissionTreeNode) GetChildren() []*PermissionTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// 获取用户权限请求
type GetMemberPermissionsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成员ID
	MemberId int64 `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty" dc:"成员ID" v:"required|min:1#成员ID不能为空|成员ID必须大于0"` // v:required|min:1#成员ID不能为空|成员ID必须大于0
	// 权限类型:permissions_type (不传返回所有类型)
	PermTypes     []string `protobuf:"bytes,2,rep,name=PermTypes,proto3" json:"PermTypes,omitempty" dc:"权限类型:permissions_type (不传返回所有类型)"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberPermissionsReq) Reset() {
	*x = GetMemberPermissionsReq{}
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberPermissionsReq) ProtoMessage() {}

func (x *GetMemberPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberPermissionsReq.ProtoReflect.Descriptor instead.
func (*GetMemberPermissionsReq) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *GetMemberPermissionsReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *GetMemberPermissionsReq) GetPermTypes() []string {
	if x != nil {
		return x.PermTypes
	}
	return nil
}

// 获取用户权限响应
type GetMemberPermissionsRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 权限标识列表
	Permissions   []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty" dc:"权限标识列表"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberPermissionsRes) Reset() {
	*x = GetMemberPermissionsRes{}
	mi := &file_permission_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberPermissionsRes) ProtoMessage() {}

func (x *GetMemberPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_permission_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberPermissionsRes.ProtoReflect.Descriptor instead.
func (*GetMemberPermissionsRes) Descriptor() ([]byte, []int) {
	return file_permission_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *GetMemberPermissionsRes) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_permission_v1_permission_proto protoreflect.FileDescriptor

const file_permission_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1epermission/v1/permission.proto\x12\rpermission.v1\"P\n" +
	"\x18AssignRolePermissionsReq\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\x12\x1c\n" +
	"\tpermCodes\x18\x02 \x03(\tR\tpermCodes\"4\n" +
	"\x18AssignRolePermissionsRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x15GetRolePermissionsReq\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\x03R\x06roleId\"=\n" +
	"\x15GetRolePermissionsRes\x12$\n" +
	"\rpermissionIds\x18\x01 \x03(\x03R\rpermissionIds\"\x16\n" +
	"\x14GetPermissionTreeReq\"M\n" +
	"\x14GetPermissionTreeRes\x125\n" +
	"\x04tree\x18\x01 \x03(\v2!.permission.v1.PermissionTreeNodeR\x04tree\"\xaf\x01\n" +
	"\x12PermissionTreeNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bpermCode\x18\x02 \x01(\tR\bpermCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpermType\x18\x04 \x01(\tR\bpermType\x12=\n" +
	"\bchildren\x18\x05 \x03(\v2!.permission.v1.PermissionTreeNodeR\bchildren\"S\n" +
	"\x17GetMemberPermissionsReq\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12\x1c\n" +
	"\tPermTypes\x18\x02 \x03(\tR\tPermTypes\";\n" +
	"\x17GetMemberPermissionsRes\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions2\xa0\x03\n" +
	"\n" +
	"Permission\x12i\n" +
	"\x15AssignRolePermissions\x12'.permission.v1.AssignRolePermissionsReq\x1a'.permission.v1.AssignRolePermissionsRes\x12`\n" +
	"\x12GetRolePermissions\x12$.permission.v1.GetRolePermissionsReq\x1a$.permission.v1.GetRolePermissionsRes\x12]\n" +
	"\x11GetPermissionTree\x12#.permission.v1.GetPermissionTreeReq\x1a#.permission.v1.GetPermissionTreeRes\x12f\n" +
	"\x14GetMemberPermissions\x12&.permission.v1.GetMemberPermissionsReq\x1a&.permission.v1.GetMemberPermissionsResB\x15Z\x13./api/permission/v1b\x06proto3"

var (
	file_permission_v1_permission_proto_rawDescOnce sync.Once
	file_permission_v1_permission_proto_rawDescData []byte
)

func file_permission_v1_permission_proto_rawDescGZIP() []byte {
	file_permission_v1_permission_proto_rawDescOnce.Do(func() {
		file_permission_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)))
	})
	return file_permission_v1_permission_proto_rawDescData
}

var file_permission_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_permission_v1_permission_proto_goTypes = []any{
	(*AssignRolePermissionsReq)(nil), // 0: permission.v1.AssignRolePermissionsReq
	(*AssignRolePermissionsRes)(nil), // 1: permission.v1.AssignRolePermissionsRes
	(*GetRolePermissionsReq)(nil),    // 2: permission.v1.GetRolePermissionsReq
	(*GetRolePermissionsRes)(nil),    // 3: permission.v1.GetRolePermissionsRes
	(*GetPermissionTreeReq)(nil),     // 4: permission.v1.GetPermissionTreeReq
	(*GetPermissionTreeRes)(nil),     // 5: permission.v1.GetPermissionTreeRes
	(*PermissionTreeNode)(nil),       // 6: permission.v1.PermissionTreeNode
	(*GetMemberPermissionsReq)(nil),  // 7: permission.v1.GetMemberPermissionsReq
	(*GetMemberPermissionsRes)(nil),  // 8: permission.v1.GetMemberPermissionsRes
}
var file_permission_v1_permission_proto_depIdxs = []int32{
	6, // 0: permission.v1.GetPermissionTreeRes.tree:type_name -> permission.v1.PermissionTreeNode
	6, // 1: permission.v1.PermissionTreeNode.children:type_name -> permission.v1.PermissionTreeNode
	0, // 2: permission.v1.Permission.AssignRolePermissions:input_type -> permission.v1.AssignRolePermissionsReq
	2, // 3: permission.v1.Permission.GetRolePermissions:input_type -> permission.v1.GetRolePermissionsReq
	4, // 4: permission.v1.Permission.GetPermissionTree:input_type -> permission.v1.GetPermissionTreeReq
	7, // 5: permission.v1.Permission.GetMemberPermissions:input_type -> permission.v1.GetMemberPermissionsReq
	1, // 6: permission.v1.Permission.AssignRolePermissions:output_type -> permission.v1.AssignRolePermissionsRes
	3, // 7: permission.v1.Permission.GetRolePermissions:output_type -> permission.v1.GetRolePermissionsRes
	5, // 8: permission.v1.Permission.GetPermissionTree:output_type -> permission.v1.GetPermissionTreeRes
	8, // 9: permission.v1.Permission.GetMemberPermissions:output_type -> permission.v1.GetMemberPermissionsRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_permission_v1_permission_proto_init() }
func file_permission_v1_permission_proto_init() {
	if File_permission_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permission_v1_permission_proto_rawDesc), len(file_permission_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permission_v1_permission_proto_goTypes,
		DependencyIndexes: file_permission_v1_permission_proto_depIdxs,
		MessageInfos:      file_permission_v1_permission_proto_msgTypes,
	}.Build()
	File_permission_v1_permission_proto = out.File
	file_permission_v1_permission_proto_goTypes = nil
	file_permission_v1_permission_proto_depIdxs = nil
}
