// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: pbentity/system_enum_type.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemEnumType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                  //
	EnumType      string                 `protobuf:"bytes,2,opt,name=EnumType,proto3" json:"EnumType,omitempty" dc:"枚举类型，如 user_type"` // 枚举类型，如 user_type
	EnumTypeDesc  string                 `protobuf:"bytes,3,opt,name=EnumTypeDesc,proto3" json:"EnumTypeDesc,omitempty" dc:"枚举类型说明"`   // 枚举类型说明
	IsEnabled     int32                  `protobuf:"varint,4,opt,name=IsEnabled,proto3" json:"IsEnabled,omitempty" dc:"是否启用0:否,1:是"`   // 是否启用0:否,1:是
	IsDeleted     uint32                 `protobuf:"varint,5,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"是否删除0:否,1:是"`   // 是否删除0:否,1:是
	CreateBy      uint64                 `protobuf:"varint,6,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`             // 创建人
	UpdateBy      uint64                 `protobuf:"varint,7,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`             // 修改人
	DeleteBy      uint64                 `protobuf:"varint,8,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`             // 删除人
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`             // 创建时间
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`            // 更新时间
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`          // 删除时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemEnumType) Reset() {
	*x = SystemEnumType{}
	mi := &file_pbentity_system_enum_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEnumType) ProtoMessage() {}

func (x *SystemEnumType) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_system_enum_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEnumType.ProtoReflect.Descriptor instead.
func (*SystemEnumType) Descriptor() ([]byte, []int) {
	return file_pbentity_system_enum_type_proto_rawDescGZIP(), []int{0}
}

func (x *SystemEnumType) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SystemEnumType) GetEnumType() string {
	if x != nil {
		return x.EnumType
	}
	return ""
}

func (x *SystemEnumType) GetEnumTypeDesc() string {
	if x != nil {
		return x.EnumTypeDesc
	}
	return ""
}

func (x *SystemEnumType) GetIsEnabled() int32 {
	if x != nil {
		return x.IsEnabled
	}
	return 0
}

func (x *SystemEnumType) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *SystemEnumType) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *SystemEnumType) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *SystemEnumType) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *SystemEnumType) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *SystemEnumType) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *SystemEnumType) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_system_enum_type_proto protoreflect.FileDescriptor

const file_pbentity_system_enum_type_proto_rawDesc = "" +
	"\n" +
	"\x1fpbentity/system_enum_type.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x03\n" +
	"\x0eSystemEnumType\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x1a\n" +
	"\bEnumType\x18\x02 \x01(\tR\bEnumType\x12\"\n" +
	"\fEnumTypeDesc\x18\x03 \x01(\tR\fEnumTypeDesc\x12\x1c\n" +
	"\tIsEnabled\x18\x04 \x01(\x05R\tIsEnabled\x12\x1c\n" +
	"\tIsDeleted\x18\x05 \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\x06 \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\a \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\b \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\"Z freeroam/app/system/api/pbentityb\x06proto3"

var (
	file_pbentity_system_enum_type_proto_rawDescOnce sync.Once
	file_pbentity_system_enum_type_proto_rawDescData []byte
)

func file_pbentity_system_enum_type_proto_rawDescGZIP() []byte {
	file_pbentity_system_enum_type_proto_rawDescOnce.Do(func() {
		file_pbentity_system_enum_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_system_enum_type_proto_rawDesc), len(file_pbentity_system_enum_type_proto_rawDesc)))
	})
	return file_pbentity_system_enum_type_proto_rawDescData
}

var file_pbentity_system_enum_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_system_enum_type_proto_goTypes = []any{
	(*SystemEnumType)(nil),        // 0: pbentity.SystemEnumType
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_system_enum_type_proto_depIdxs = []int32{
	1, // 0: pbentity.SystemEnumType.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.SystemEnumType.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.SystemEnumType.DeletedAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_system_enum_type_proto_init() }
func file_pbentity_system_enum_type_proto_init() {
	if File_pbentity_system_enum_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_system_enum_type_proto_rawDesc), len(file_pbentity_system_enum_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_system_enum_type_proto_goTypes,
		DependencyIndexes: file_pbentity_system_enum_type_proto_depIdxs,
		MessageInfos:      file_pbentity_system_enum_type_proto_msgTypes,
	}.Build()
	File_pbentity_system_enum_type_proto = out.File
	file_pbentity_system_enum_type_proto_goTypes = nil
	file_pbentity_system_enum_type_proto_depIdxs = nil
}
