// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: org/v1/org.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID
	// v:required|integer|min:1#组织ID不能为空|组织ID必须是整数|组织ID不能小于1
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"组织ID" v:"required|integer|min:1#组织ID不能为空|组织ID必须是整数|组织ID不能小于1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	mi := &file_org_v1_org_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"组织ID"`
	// 上级id
	ParentId int64 `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty" dc:"上级id"`
	// 组织名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"组织名称"`
	// 组织编码
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty" dc:"组织编码"`
	// 组织分类
	Type int64 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty" dc:"组织分类"`
	// 状态
	Status int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 主管
	Supervisors   []*Supervisor `protobuf:"bytes,7,rep,name=supervisors,proto3" json:"supervisors,omitempty" dc:"主管"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	mi := &file_org_v1_org_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{1}
}

func (x *GetRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRes) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetRes) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetRes) GetSupervisors() []*Supervisor {
	if x != nil {
		return x.Supervisors
	}
	return nil
}

// 主管信息
type Supervisor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主管ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"主管ID"`
	// 主管名称
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"主管名称"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Supervisor) Reset() {
	*x = Supervisor{}
	mi := &file_org_v1_org_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supervisor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supervisor) ProtoMessage() {}

func (x *Supervisor) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supervisor.ProtoReflect.Descriptor instead.
func (*Supervisor) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{2}
}

func (x *Supervisor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Supervisor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织名，模糊搜索
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" dc:"组织名，模糊搜索"`
	// 上级id
	// v:integer|min:0#上级id必须是整数|上级id必须大于0
	ParentId *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=parentId,proto3" json:"parentId,omitempty" dc:"上级id" v:"integer|min:0#上级id必须是整数|上级id必须大于0"`
	// 组织编码
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty" dc:"组织编码"`
	// 组织分类
	// v:integer|min:0#组织分类不正确1|组织分类不正确2
	Type int64 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty" dc:"组织分类" v:"integer|min:0#组织分类不正确1|组织分类不正确2"`
	// 分页号码
	// v:min:0#分页号码错误
	Page int32 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty" dc:"分页号码" v:"min:0#分页号码错误"`
	// 分页数量，最大100
	// v:max:100#分页数量最大100条
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty" dc:"分页数量，最大100" v:"max:100#分页数量最大100条"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_org_v1_org_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{3}
}

func (x *GetListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListReq) GetParentId() *wrapperspb.Int64Value {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *GetListReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetListReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 数据列表
	List []*GetListItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" dc:"数据列表"`
	// 数据总数
	Total         int64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" dc:"数据总数"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes) Reset() {
	*x = GetListRes{}
	mi := &file_org_v1_org_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes) ProtoMessage() {}

func (x *GetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes.ProtoReflect.Descriptor instead.
func (*GetListRes) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{4}
}

func (x *GetListRes) GetList() []*GetListItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 组织ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"组织ID"`
	// 姓名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"姓名"`
	// 组织分类
	Type int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty" dc:"组织分类"`
	// 组织编码
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty" dc:"组织编码"`
	// 状态
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty" dc:"状态"`
	// 创建时间
	CreateAt      string `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty" dc:"创建时间"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListItem) Reset() {
	*x = GetListItem{}
	mi := &file_org_v1_org_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListItem) ProtoMessage() {}

func (x *GetListItem) ProtoReflect() protoreflect.Message {
	mi := &file_org_v1_org_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListItem.ProtoReflect.Descriptor instead.
func (*GetListItem) Descriptor() ([]byte, []int) {
	return file_org_v1_org_proto_rawDescGZIP(), []int{5}
}

func (x *GetListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetListItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetListItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetListItem) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

var File_org_v1_org_proto protoreflect.FileDescriptor

const file_org_v1_org_proto_rawDesc = "" +
	"\n" +
	"\x10org/v1/org.proto\x12\x06org.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x18\n" +
	"\x06GetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbe\x01\n" +
	"\x06GetRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x03R\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x124\n" +
	"\vsupervisors\x18\a \x03(\v2\x12.org.v1.SupervisorR\vsupervisors\"0\n" +
	"\n" +
	"Supervisor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xab\x01\n" +
	"\n" +
	"GetListReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\bparentId\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\bparentId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"K\n" +
	"\n" +
	"GetListRes\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.org.v1.GetListItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8d\x01\n" +
	"\vGetListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateAt\x18\x06 \x01(\tR\bcreateAt2c\n" +
	"\x03Org\x12'\n" +
	"\x03Get\x12\x0e.org.v1.GetReq\x1a\x0e.org.v1.GetRes\"\x00\x123\n" +
	"\aGetList\x12\x12.org.v1.GetListReq\x1a\x12.org.v1.GetListRes\"\x00B\x0eZ\f./api/org/v1b\x06proto3"

var (
	file_org_v1_org_proto_rawDescOnce sync.Once
	file_org_v1_org_proto_rawDescData []byte
)

func file_org_v1_org_proto_rawDescGZIP() []byte {
	file_org_v1_org_proto_rawDescOnce.Do(func() {
		file_org_v1_org_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)))
	})
	return file_org_v1_org_proto_rawDescData
}

var file_org_v1_org_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_org_v1_org_proto_goTypes = []any{
	(*GetReq)(nil),                // 0: org.v1.GetReq
	(*GetRes)(nil),                // 1: org.v1.GetRes
	(*Supervisor)(nil),            // 2: org.v1.Supervisor
	(*GetListReq)(nil),            // 3: org.v1.GetListReq
	(*GetListRes)(nil),            // 4: org.v1.GetListRes
	(*GetListItem)(nil),           // 5: org.v1.GetListItem
	(*wrapperspb.Int64Value)(nil), // 6: google.protobuf.Int64Value
}
var file_org_v1_org_proto_depIdxs = []int32{
	2, // 0: org.v1.GetRes.supervisors:type_name -> org.v1.Supervisor
	6, // 1: org.v1.GetListReq.parentId:type_name -> google.protobuf.Int64Value
	5, // 2: org.v1.GetListRes.list:type_name -> org.v1.GetListItem
	0, // 3: org.v1.Org.Get:input_type -> org.v1.GetReq
	3, // 4: org.v1.Org.GetList:input_type -> org.v1.GetListReq
	1, // 5: org.v1.Org.Get:output_type -> org.v1.GetRes
	4, // 6: org.v1.Org.GetList:output_type -> org.v1.GetListRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_org_v1_org_proto_init() }
func file_org_v1_org_proto_init() {
	if File_org_v1_org_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_v1_org_proto_rawDesc), len(file_org_v1_org_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_v1_org_proto_goTypes,
		DependencyIndexes: file_org_v1_org_proto_depIdxs,
		MessageInfos:      file_org_v1_org_proto_msgTypes,
	}.Build()
	File_org_v1_org_proto = out.File
	file_org_v1_org_proto_goTypes = nil
	file_org_v1_org_proto_depIdxs = nil
}
