// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: org/v1/org.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Org_GetOrgTree_FullMethodName = "/org.v1.Org/GetOrgTree"
	Org_ListOrg_FullMethodName    = "/org.v1.Org/ListOrg"
	Org_GetOrg_FullMethodName     = "/org.v1.Org/GetOrg"
	Org_CreateOrg_FullMethodName  = "/org.v1.Org/CreateOrg"
	Org_UpdateOrg_FullMethodName  = "/org.v1.Org/UpdateOrg"
	Org_DeleteOrg_FullMethodName  = "/org.v1.Org/DeleteOrg"
	Org_MoveOrg_FullMethodName    = "/org.v1.Org/MoveOrg"
)

// OrgClient is the client API for Org service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrgClient interface {
	// 获取组织树
	GetOrgTree(ctx context.Context, in *GetOrgTreeReq, opts ...grpc.CallOption) (*GetOrgTreeRes, error)
	// 获取组织列表
	ListOrg(ctx context.Context, in *ListOrgReq, opts ...grpc.CallOption) (*ListOrgRes, error)
	// 获取组织详情
	GetOrg(ctx context.Context, in *GetOrgReq, opts ...grpc.CallOption) (*GetOrgRes, error)
	// 新建组织
	CreateOrg(ctx context.Context, in *CreateOrgReq, opts ...grpc.CallOption) (*CreateOrgRes, error)
	// 编辑组织
	UpdateOrg(ctx context.Context, in *UpdateOrgReq, opts ...grpc.CallOption) (*UpdateOrgRes, error)
	// 删除组织
	DeleteOrg(ctx context.Context, in *DeleteOrgReq, opts ...grpc.CallOption) (*DeleteOrgRes, error)
	// 拖拽移动/排序
	MoveOrg(ctx context.Context, in *MoveOrgReq, opts ...grpc.CallOption) (*MoveOrgRes, error)
}

type orgClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgClient(cc grpc.ClientConnInterface) OrgClient {
	return &orgClient{cc}
}

func (c *orgClient) GetOrgTree(ctx context.Context, in *GetOrgTreeReq, opts ...grpc.CallOption) (*GetOrgTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgTreeRes)
	err := c.cc.Invoke(ctx, Org_GetOrgTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) ListOrg(ctx context.Context, in *ListOrgReq, opts ...grpc.CallOption) (*ListOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgRes)
	err := c.cc.Invoke(ctx, Org_ListOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) GetOrg(ctx context.Context, in *GetOrgReq, opts ...grpc.CallOption) (*GetOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrgRes)
	err := c.cc.Invoke(ctx, Org_GetOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) CreateOrg(ctx context.Context, in *CreateOrgReq, opts ...grpc.CallOption) (*CreateOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrgRes)
	err := c.cc.Invoke(ctx, Org_CreateOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) UpdateOrg(ctx context.Context, in *UpdateOrgReq, opts ...grpc.CallOption) (*UpdateOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrgRes)
	err := c.cc.Invoke(ctx, Org_UpdateOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) DeleteOrg(ctx context.Context, in *DeleteOrgReq, opts ...grpc.CallOption) (*DeleteOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrgRes)
	err := c.cc.Invoke(ctx, Org_DeleteOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) MoveOrg(ctx context.Context, in *MoveOrgReq, opts ...grpc.CallOption) (*MoveOrgRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveOrgRes)
	err := c.cc.Invoke(ctx, Org_MoveOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgServer is the server API for Org service.
// All implementations must embed UnimplementedOrgServer
// for forward compatibility.
type OrgServer interface {
	// 获取组织树
	GetOrgTree(context.Context, *GetOrgTreeReq) (*GetOrgTreeRes, error)
	// 获取组织列表
	ListOrg(context.Context, *ListOrgReq) (*ListOrgRes, error)
	// 获取组织详情
	GetOrg(context.Context, *GetOrgReq) (*GetOrgRes, error)
	// 新建组织
	CreateOrg(context.Context, *CreateOrgReq) (*CreateOrgRes, error)
	// 编辑组织
	UpdateOrg(context.Context, *UpdateOrgReq) (*UpdateOrgRes, error)
	// 删除组织
	DeleteOrg(context.Context, *DeleteOrgReq) (*DeleteOrgRes, error)
	// 拖拽移动/排序
	MoveOrg(context.Context, *MoveOrgReq) (*MoveOrgRes, error)
	mustEmbedUnimplementedOrgServer()
}

// UnimplementedOrgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrgServer struct{}

func (UnimplementedOrgServer) GetOrgTree(context.Context, *GetOrgTreeReq) (*GetOrgTreeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrgTree not implemented")
}
func (UnimplementedOrgServer) ListOrg(context.Context, *ListOrgReq) (*ListOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrg not implemented")
}
func (UnimplementedOrgServer) GetOrg(context.Context, *GetOrgReq) (*GetOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrg not implemented")
}
func (UnimplementedOrgServer) CreateOrg(context.Context, *CreateOrgReq) (*CreateOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrg not implemented")
}
func (UnimplementedOrgServer) UpdateOrg(context.Context, *UpdateOrgReq) (*UpdateOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrg not implemented")
}
func (UnimplementedOrgServer) DeleteOrg(context.Context, *DeleteOrgReq) (*DeleteOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrg not implemented")
}
func (UnimplementedOrgServer) MoveOrg(context.Context, *MoveOrgReq) (*MoveOrgRes, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveOrg not implemented")
}
func (UnimplementedOrgServer) mustEmbedUnimplementedOrgServer() {}
func (UnimplementedOrgServer) testEmbeddedByValue()             {}

// UnsafeOrgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrgServer will
// result in compilation errors.
type UnsafeOrgServer interface {
	mustEmbedUnimplementedOrgServer()
}

func RegisterOrgServer(s grpc.ServiceRegistrar, srv OrgServer) {
	// If the following call panics, it indicates UnimplementedOrgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Org_ServiceDesc, srv)
}

func _Org_GetOrgTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).GetOrgTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_GetOrgTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).GetOrgTree(ctx, req.(*GetOrgTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_ListOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).ListOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_ListOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).ListOrg(ctx, req.(*ListOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_GetOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).GetOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_GetOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).GetOrg(ctx, req.(*GetOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_CreateOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).CreateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_CreateOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).CreateOrg(ctx, req.(*CreateOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_UpdateOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).UpdateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_UpdateOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).UpdateOrg(ctx, req.(*UpdateOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_DeleteOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).DeleteOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_DeleteOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).DeleteOrg(ctx, req.(*DeleteOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_MoveOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveOrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).MoveOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Org_MoveOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).MoveOrg(ctx, req.(*MoveOrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Org_ServiceDesc is the grpc.ServiceDesc for Org service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Org_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.v1.Org",
	HandlerType: (*OrgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrgTree",
			Handler:    _Org_GetOrgTree_Handler,
		},
		{
			MethodName: "ListOrg",
			Handler:    _Org_ListOrg_Handler,
		},
		{
			MethodName: "GetOrg",
			Handler:    _Org_GetOrg_Handler,
		},
		{
			MethodName: "CreateOrg",
			Handler:    _Org_CreateOrg_Handler,
		},
		{
			MethodName: "UpdateOrg",
			Handler:    _Org_UpdateOrg_Handler,
		},
		{
			MethodName: "DeleteOrg",
			Handler:    _Org_DeleteOrg_Handler,
		},
		{
			MethodName: "MoveOrg",
			Handler:    _Org_MoveOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/v1/org.proto",
}
