// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: permissions/v1/permissions.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Permissions_AssignRolePermissions_FullMethodName = "/permissions.v1.Permissions/AssignRolePermissions"
	Permissions_GetRolePermissions_FullMethodName    = "/permissions.v1.Permissions/GetRolePermissions"
	Permissions_GetPermissionsTree_FullMethodName    = "/permissions.v1.Permissions/GetPermissionsTree"
	Permissions_GetMemberPermissions_FullMethodName  = "/permissions.v1.Permissions/GetMemberPermissions"
)

// PermissionsClient is the client API for Permissions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionsClient interface {
	// 角色权限分配
	AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsReq, opts ...grpc.CallOption) (*AssignRolePermissionsRes, error)
	// 查询角色权限
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsRes, error)
	// 查询权限资源树
	GetPermissionsTree(ctx context.Context, in *GetPermissionsTreeReq, opts ...grpc.CallOption) (*GetPermissionsTreeRes, error)
	// 获取用户权限
	GetMemberPermissions(ctx context.Context, in *GetMemberPermissionsReq, opts ...grpc.CallOption) (*GetMemberPermissionsRes, error)
}

type permissionsClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionsClient(cc grpc.ClientConnInterface) PermissionsClient {
	return &permissionsClient{cc}
}

func (c *permissionsClient) AssignRolePermissions(ctx context.Context, in *AssignRolePermissionsReq, opts ...grpc.CallOption) (*AssignRolePermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRolePermissionsRes)
	err := c.cc.Invoke(ctx, Permissions_AssignRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsReq, opts ...grpc.CallOption) (*GetRolePermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsRes)
	err := c.cc.Invoke(ctx, Permissions_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetPermissionsTree(ctx context.Context, in *GetPermissionsTreeReq, opts ...grpc.CallOption) (*GetPermissionsTreeRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionsTreeRes)
	err := c.cc.Invoke(ctx, Permissions_GetPermissionsTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionsClient) GetMemberPermissions(ctx context.Context, in *GetMemberPermissionsReq, opts ...grpc.CallOption) (*GetMemberPermissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberPermissionsRes)
	err := c.cc.Invoke(ctx, Permissions_GetMemberPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionsServer is the server API for Permissions service.
// All implementations must embed UnimplementedPermissionsServer
// for forward compatibility.
type PermissionsServer interface {
	// 角色权限分配
	AssignRolePermissions(context.Context, *AssignRolePermissionsReq) (*AssignRolePermissionsRes, error)
	// 查询角色权限
	GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsRes, error)
	// 查询权限资源树
	GetPermissionsTree(context.Context, *GetPermissionsTreeReq) (*GetPermissionsTreeRes, error)
	// 获取用户权限
	GetMemberPermissions(context.Context, *GetMemberPermissionsReq) (*GetMemberPermissionsRes, error)
	mustEmbedUnimplementedPermissionsServer()
}

// UnimplementedPermissionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionsServer struct{}

func (UnimplementedPermissionsServer) AssignRolePermissions(context.Context, *AssignRolePermissionsReq) (*AssignRolePermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRolePermissions not implemented")
}
func (UnimplementedPermissionsServer) GetRolePermissions(context.Context, *GetRolePermissionsReq) (*GetRolePermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedPermissionsServer) GetPermissionsTree(context.Context, *GetPermissionsTreeReq) (*GetPermissionsTreeRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionsTree not implemented")
}
func (UnimplementedPermissionsServer) GetMemberPermissions(context.Context, *GetMemberPermissionsReq) (*GetMemberPermissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberPermissions not implemented")
}
func (UnimplementedPermissionsServer) mustEmbedUnimplementedPermissionsServer() {}
func (UnimplementedPermissionsServer) testEmbeddedByValue()                     {}

// UnsafePermissionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionsServer will
// result in compilation errors.
type UnsafePermissionsServer interface {
	mustEmbedUnimplementedPermissionsServer()
}

func RegisterPermissionsServer(s grpc.ServiceRegistrar, srv PermissionsServer) {
	// If the following call panics, it indicates UnimplementedPermissionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Permissions_ServiceDesc, srv)
}

func _Permissions_AssignRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).AssignRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_AssignRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).AssignRolePermissions(ctx, req.(*AssignRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetRolePermissions(ctx, req.(*GetRolePermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetPermissionsTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionsTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetPermissionsTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetPermissionsTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetPermissionsTree(ctx, req.(*GetPermissionsTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Permissions_GetMemberPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionsServer).GetMemberPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Permissions_GetMemberPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionsServer).GetMemberPermissions(ctx, req.(*GetMemberPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Permissions_ServiceDesc is the grpc.ServiceDesc for Permissions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Permissions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permissions.v1.Permissions",
	HandlerType: (*PermissionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRolePermissions",
			Handler:    _Permissions_AssignRolePermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _Permissions_GetRolePermissions_Handler,
		},
		{
			MethodName: "GetPermissionsTree",
			Handler:    _Permissions_GetPermissionsTree_Handler,
		},
		{
			MethodName: "GetMemberPermissions",
			Handler:    _Permissions_GetMemberPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permissions/v1/permissions.proto",
}
