// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pbentity/admin_user.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"主键"`                                  // 主键
	UserId            uint64                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户ID"`                        // 用户ID
	Username          string                 `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty" dc:"用户名"`                      // 用户名
	Name              string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty" dc:"名称"`                               // 名称
	ResetPasswordTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ResetPasswordTime,proto3" json:"ResetPasswordTime,omitempty" dc:"重置密码时间"` // 重置密码时间
	Status            uint32                 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty" dc:"状态：0未启用，1已启用，2禁止登陆"`          // 状态：0未启用，1已启用，2禁止登陆
	Super             uint32                 `protobuf:"varint,7,opt,name=Super,proto3" json:"Super,omitempty" dc:"超级管理员，0否1是"`                    // 超级管理员，0否1是
	IsDeleted         uint32                 `protobuf:"varint,8,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty" dc:"数据状态0正常1删除"`            // 数据状态0正常1删除
	CreateBy          uint64                 `protobuf:"varint,9,opt,name=CreateBy,proto3" json:"CreateBy,omitempty" dc:"创建人"`                     // 创建人
	UpdateBy          uint64                 `protobuf:"varint,10,opt,name=UpdateBy,proto3" json:"UpdateBy,omitempty" dc:"修改人"`                    // 修改人
	DeleteBy          uint64                 `protobuf:"varint,11,opt,name=DeleteBy,proto3" json:"DeleteBy,omitempty" dc:"删除人"`                    // 删除人
	CreateAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=CreateAt,proto3" json:"CreateAt,omitempty" dc:"创建时间"`                    // 创建时间
	UpdateAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty" dc:"更新时间"`                    // 更新时间
	DeletedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty" dc:"删除时间"`                  // 删除时间
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_pbentity_admin_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_admin_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_pbentity_admin_user_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminUser) GetResetPasswordTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetPasswordTime
	}
	return nil
}

func (x *AdminUser) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminUser) GetSuper() uint32 {
	if x != nil {
		return x.Super
	}
	return 0
}

func (x *AdminUser) GetIsDeleted() uint32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

func (x *AdminUser) GetCreateBy() uint64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *AdminUser) GetUpdateBy() uint64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

func (x *AdminUser) GetDeleteBy() uint64 {
	if x != nil {
		return x.DeleteBy
	}
	return 0
}

func (x *AdminUser) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *AdminUser) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *AdminUser) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_pbentity_admin_user_proto protoreflect.FileDescriptor

const file_pbentity_admin_user_proto_rawDesc = "" +
	"\n" +
	"\x19pbentity/admin_user.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x03\n" +
	"\tAdminUser\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x04R\x06UserId\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12H\n" +
	"\x11ResetPasswordTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11ResetPasswordTime\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\rR\x06Status\x12\x14\n" +
	"\x05Super\x18\a \x01(\rR\x05Super\x12\x1c\n" +
	"\tIsDeleted\x18\b \x01(\rR\tIsDeleted\x12\x1a\n" +
	"\bCreateBy\x18\t \x01(\x04R\bCreateBy\x12\x1a\n" +
	"\bUpdateBy\x18\n" +
	" \x01(\x04R\bUpdateBy\x12\x1a\n" +
	"\bDeleteBy\x18\v \x01(\x04R\bDeleteBy\x126\n" +
	"\bCreateAt\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x128\n" +
	"\tDeletedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAtB\x1bZ\x19bbk/app/user/api/pbentityb\x06proto3"

var (
	file_pbentity_admin_user_proto_rawDescOnce sync.Once
	file_pbentity_admin_user_proto_rawDescData []byte
)

func file_pbentity_admin_user_proto_rawDescGZIP() []byte {
	file_pbentity_admin_user_proto_rawDescOnce.Do(func() {
		file_pbentity_admin_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_admin_user_proto_rawDesc), len(file_pbentity_admin_user_proto_rawDesc)))
	})
	return file_pbentity_admin_user_proto_rawDescData
}

var file_pbentity_admin_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_admin_user_proto_goTypes = []any{
	(*AdminUser)(nil),             // 0: pbentity.AdminUser
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_admin_user_proto_depIdxs = []int32{
	1, // 0: pbentity.AdminUser.ResetPasswordTime:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.AdminUser.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.AdminUser.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 3: pbentity.AdminUser.DeletedAt:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pbentity_admin_user_proto_init() }
func file_pbentity_admin_user_proto_init() {
	if File_pbentity_admin_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_admin_user_proto_rawDesc), len(file_pbentity_admin_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_admin_user_proto_goTypes,
		DependencyIndexes: file_pbentity_admin_user_proto_depIdxs,
		MessageInfos:      file_pbentity_admin_user_proto_msgTypes,
	}.Build()
	File_pbentity_admin_user_proto = out.File
	file_pbentity_admin_user_proto_goTypes = nil
	file_pbentity_admin_user_proto_depIdxs = nil
}
