// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: config/v1/config.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByCodeReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置编码，如 token_validity_period
	ConfigCode    string `protobuf:"bytes,1,opt,name=configCode,proto3" json:"configCode,omitempty" dc:"配置编码，如 token_validity_period" v:"required#配置编码不能为空"` // v:required#配置编码不能为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByCodeReq) Reset() {
	*x = GetByCodeReq{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByCodeReq) ProtoMessage() {}

func (x *GetByCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByCodeReq.ProtoReflect.Descriptor instead.
func (*GetByCodeReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetByCodeReq) GetConfigCode() string {
	if x != nil {
		return x.ConfigCode
	}
	return ""
}

type GetByCodeRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置值，如 60
	ConfigValue   string `protobuf:"bytes,1,opt,name=configValue,proto3" json:"configValue,omitempty" dc:"配置值，如 60"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByCodeRes) Reset() {
	*x = GetByCodeRes{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByCodeRes) ProtoMessage() {}

func (x *GetByCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByCodeRes.ProtoReflect.Descriptor instead.
func (*GetByCodeRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetByCodeRes) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\".\n" +
	"\fGetByCodeReq\x12\x1e\n" +
	"\n" +
	"configCode\x18\x01 \x01(\tR\n" +
	"configCode\"0\n" +
	"\fGetByCodeRes\x12 \n" +
	"\vconfigValue\x18\x01 \x01(\tR\vconfigValue2G\n" +
	"\x06Config\x12=\n" +
	"\tGetByCode\x12\x17.config.v1.GetByCodeReq\x1a\x17.config.v1.GetByCodeResB\x11Z\x0f./api/config/v1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_v1_config_proto_goTypes = []any{
	(*GetByCodeReq)(nil), // 0: config.v1.GetByCodeReq
	(*GetByCodeRes)(nil), // 1: config.v1.GetByCodeRes
}
var file_config_v1_config_proto_depIdxs = []int32{
	0, // 0: config.v1.Config.GetByCode:input_type -> config.v1.GetByCodeReq
	1, // 1: config.v1.Config.GetByCode:output_type -> config.v1.GetByCodeRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
