// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"freeroam/app/gateway/api/role"
	oRole "freeroam/app/org/api/role/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	RoleRpcService oRole.RoleClient
}

func NewV1() role.IRoleV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		RoleRpcService: oRole.NewRoleClient(conn),
	}
}
