
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:ZHYstc_00.888@tcp(124.221.249.230:13306)/freeroam?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
        descriptionTag: true
        removePrefix: "bbk_"
        tables: "bbk_admin_user,bbk_user_base"
    pbentity:
      - link: "mysql:root:ZHYstc_00.888@tcp(124.221.249.230:13306)/freeroam?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
        removePrefix: "bbk_"
        tables: "bbk_admin_user,bbk_user_base"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app