// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bbk/app/user/internal/dao/internal"
)

// userBaseDao is the data access object for the table bbk_user_base.
// You can define custom methods on it to extend its functionality as needed.
type userBaseDao struct {
	*internal.UserBaseDao
}

var (
	// UserBase is a globally accessible object for table bbk_user_base operations.
	UserBase = userBaseDao{internal.NewUserBaseDao()}
)

// Add your custom methods and functionality below.
