// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"freeroam/app/gateway/api/auth"
	"freeroam/app/gateway/internal/service"
)

type ControllerV1 struct {
	AuthService service.IAuth
}

func NewV1() auth.IAuthV1 {
	return &ControllerV1{
		AuthService: service.Auth(),
	}
}
