// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package position

import (
	"freeroam/app/gateway/api/position"
	oPosition "freeroam/app/org/api/position/v1"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	PositionRpcService oPosition.PositionClient
}

func NewV1() position.IPositionV1 {
	conn := grpcx.Client.MustNewGrpcClientConn("org")
	return &ControllerV1{
		PositionRpcService: oPosition.NewPositionClient(conn),
	}
}
