syntax = "proto3";

package permissions.v1;

option go_package = "./api/permissions/v1";

service Permissions {
  // 角色权限分配
  rpc AssignRolePermissions(AssignRolePermissionsReq) returns (AssignRolePermissionsRes);
  // 查询角色权限
  rpc GetRolePermissions(GetRolePermissionsReq) returns (GetRolePermissionsRes);
  // 查询权限资源树
  rpc GetPermissionsTree(GetPermissionsTreeReq) returns (GetPermissionsTreeRes);
  // 获取用户权限
  rpc GetMemberPermissions(GetMemberPermissionsReq) returns (GetMemberPermissionsRes);
}

// 角色权限分配请求
message AssignRolePermissionsReq {
  // 角色ID
  int64 roleId = 1; // v:required|min:1#角色ID不能为空|角色ID必须大于0
  // 权限标识列表
  repeated string permCodes = 2; // v:required|min-length:1#权限标识列表不能为空|至少需要一个权限标识
}

// 角色权限分配响应
message AssignRolePermissionsRes {
  // 是否成功
  bool success = 1;
}

// 查询角色权限请求
message GetRolePermissionsReq {
  // 角色ID
  int64 roleId = 1; // v:required|min:1#角色ID不能为空|角色ID必须大于0
}

// 查询角色权限响应
message GetRolePermissionsRes {
  // 权限ID列表
  repeated int64 permissionsIds = 1;
}

// 查询权限资源树请求
message GetPermissionsTreeReq {
  // 空请求，返回完整权限树
}

// 查询权限资源树响应
message GetPermissionsTreeRes {
  // 权限树
  repeated PermissionsTreeNode tree = 1;
}

// 权限树节点
message PermissionsTreeNode {
  // 权限ID
  int64 id = 1;
  // 权限标识
  string permCode = 2;
  // 权限名称
  string name = 3;
  // 权限类型:permissions_type
  string permType = 4;
  // 子节点
  repeated PermissionsTreeNode children = 5;
}

// 获取用户权限请求
message GetMemberPermissionsReq {
  // 成员ID
  int64 MemberId = 1; // v:required|min:1#成员ID不能为空|成员ID必须大于0
  // 权限类型:permissions_type 空返回所有类型
  repeated string PermType = 2;
}

// 获取用户权限响应
message GetMemberPermissionsRes {
  // 权限标识列表
  repeated string permissions = 1;
}
